"""Phase 87C developer environment — cleanup categories and classification.

Advisory/planning only. No real scanning. No cleanup. No deletion.
"""

from __future__ import annotations

from typing import Any

from umh.workstation_optimization.contracts import (
    OptimizationActionType,
    OptimizationApprovalRequirement,
    OptimizationRiskLevel,
    _ws_id,
)


_DEV_CLEANUP_CATEGORIES: list[dict[str, Any]] = [
    {
        "name": "node_modules",
        "description": "JavaScript dependency folders — 200-500 MB each, regenerated by npm/yarn install",
        "risk": "low",
        "typical_size": "200 MB - 2 GB per project",
    },
    {
        "name": "python_venvs",
        "description": "Python virtual environments — recreated by python -m venv",
        "risk": "low",
        "typical_size": "100 MB - 1 GB each",
    },
    {
        "name": "package_caches",
        "description": "npm, pip, cargo, brew, yarn caches — shared across projects",
        "risk": "low",
        "typical_size": "1-10 GB total",
    },
    {
        "name": "docker_images",
        "description": "Docker images including unused/dangling — can accumulate rapidly",
        "risk": "medium",
        "typical_size": "5-50 GB total",
    },
    {
        "name": "docker_containers",
        "description": "Stopped Docker containers — safe to remove if not needed",
        "risk": "low",
        "typical_size": "Minimal disk but clutter",
    },
    {
        "name": "docker_volumes",
        "description": "Docker volumes may contain databases and persistent state — HIGH RISK",
        "risk": "high",
        "typical_size": "Variable — may contain irreplaceable data",
    },
    {
        "name": "build_artifacts",
        "description": "Compiled outputs, dist/, build/, .next/, target/ — regenerated by build",
        "risk": "low",
        "typical_size": "50 MB - 2 GB per project",
    },
    {
        "name": "logs",
        "description": "Application and build logs — usually safe to remove",
        "risk": "low",
        "typical_size": "10 MB - 5 GB",
    },
    {
        "name": "duplicate_repos",
        "description": "Multiple clones of same repository in different locations",
        "risk": "low",
        "typical_size": "Variable",
    },
    {
        "name": "old_replit_exports",
        "description": "Exported Replit projects no longer actively developed",
        "risk": "low",
        "typical_size": "Variable",
    },
    {
        "name": "ide_workspace_clutter",
        "description": "Cursor, VS Code, JetBrains workspace metadata, history, cache",
        "risk": "low",
        "typical_size": "100 MB - 2 GB total",
    },
    {
        "name": "claude_code_logs",
        "description": "Claude Code session transcripts and logs in ~/.claude/",
        "risk": "medium",
        "typical_size": "100 MB - 5 GB",
    },
    {
        "name": "temp_generated_files",
        "description": "Temporary outputs from code generation, testing, debugging",
        "risk": "low",
        "typical_size": "Variable",
    },
]


def build_developer_environment_cleanup_categories() -> list[dict[str, Any]]:
    return [{**cat, "category_id": _ws_id("dcat")} for cat in _DEV_CLEANUP_CATEGORIES]


def classify_developer_artifact(
    name: str | None = None,
    path_hint: str | None = None,
    context: str | None = None,
) -> str:
    hints = " ".join(filter(None, [name, path_hint, context])).lower()
    if not hints:
        return "unknown"
    if any(k in hints for k in ("node_modules",)):
        return "node_modules"
    if any(k in hints for k in ("venv", ".venv", "virtualenv", "env/lib/python")):
        return "python_venv"
    if any(k in hints for k in (".cache/pip", ".npm", ".cargo/registry", "yarn cache")):
        return "package_cache"
    if any(k in hints for k in ("docker image", "docker volume")):
        return "docker"
    if any(k in hints for k in ("dist/", "build/", ".next/", "target/", "__pycache__")):
        return "build_artifact"
    if any(k in hints for k in (".log", "logs/", "log/")):
        return "log"
    if any(k in hints for k in (".git",)):
        return "source_code"
    if any(k in hints for k in (".py", ".js", ".ts", ".rs", ".go", "src/")):
        return "source_code"
    if any(k in hints for k in ("database", ".sqlite", ".db", "postgres", "volume")):
        return "database"
    return "unknown"


def recommend_developer_cleanup_action(classification: str) -> dict[str, Any]:
    if classification == "source_code":
        return {
            "action": "preserve",
            "approval": "disabled",
            "risk": "high",
            "reason": "Source code must be preserved — review before any action",
        }
    if classification == "database":
        return {
            "action": "preserve",
            "approval": "expert_review_required",
            "risk": "high",
            "reason": "Databases and volumes may contain irreplaceable data",
        }
    if classification in ("node_modules", "python_venv", "build_artifact", "log", "package_cache"):
        return {
            "action": "clear_cache",
            "approval": "batch_approval_allowed",
            "risk": "low",
            "reason": "Generated artifacts — can be regenerated from source",
        }
    if classification == "docker":
        return {
            "action": "recommend",
            "approval": "explicit_approval",
            "risk": "medium",
            "reason": "Docker images can be repulled but volumes may have data",
        }
    return {
        "action": "preserve",
        "approval": "disabled",
        "risk": "medium",
        "reason": "Unknown developer artifact — preserve until identified",
    }


def explain_developer_bloat_sources() -> str:
    return (
        "Developer environment bloat comes from: (1) node_modules — each JS project installs its own copy of all "
        "dependencies, often 200-500 MB. (2) Python venvs — isolated environments with copies of packages. "
        "(3) Docker images — base images plus layers, 1-10 GB each, accumulate without pruning. "
        "(4) Package caches — npm, pip, cargo, brew store downloaded packages globally. "
        "(5) Build artifacts — compiled outputs that can be regenerated. "
        "(6) Logs — application and build logs that grow over time. "
        "Most of these are safe to remove and will be regenerated when needed, except Docker volumes (which may "
        "contain databases) and source code (which is irreplaceable if not pushed to remote)."
    )
