// AUTO-GENERATED by scripts/gen_voice_error_codes_ts.py — DO NOT EDIT BY HAND.
// Source of truth: substrate/execution/voice/error_codes.py::VoiceErrorCode
// Regenerate: python3 scripts/gen_voice_error_codes_ts.py
// The canonical voice error taxonomy, mirrored 1:1 from the Python enum so the
// governed WS relays a code the client already knows — no remapping, ever.


export const VOICE_ERROR_CODES = {
  EMPTY_AUDIO_BLOB: "EMPTY_AUDIO_BLOB",
  SILENT_AUDIO: "SILENT_AUDIO",
  DECODE_FAILED: "DECODE_FAILED",
  UNSUPPORTED_AUDIO_FORMAT: "UNSUPPORTED_AUDIO_FORMAT",
  VAD_NO_SPEECH: "VAD_NO_SPEECH",
  STT_FAILED: "STT_FAILED",
  CONSENT_DENIED: "CONSENT_DENIED",
  TTS_FAILED: "TTS_FAILED",
  RUNTIME_UNAVAILABLE: "RUNTIME_UNAVAILABLE",
} as const

export type VoiceErrorCode =
  (typeof VOICE_ERROR_CODES)[keyof typeof VOICE_ERROR_CODES]

export const VOICE_ERROR_CODE_VALUES: readonly VoiceErrorCode[] =
  Object.values(VOICE_ERROR_CODES)

export function isVoiceErrorCode(x: unknown): x is VoiceErrorCode {
  return typeof x === "string" && (VOICE_ERROR_CODE_VALUES as readonly string[]).includes(x)
}
