"""
Discord voice transport — bounded adapter onto the existing voice substrate.

Purpose
-------
This module is the FIRST Discord voice transport adapter. It exists so that
text-shaped utterances arriving from the Discord side (whether from a real
voice channel via Groq STT, from a slash command, or from a test fixture)
can flow into the SAME bounded seam the local workstation uses:

    inject_transcript(node_id, text, source="discord_voice", metadata={...})
        → VoiceSessionRuntime.submit_utterance
        → responder (EOS-backed if installed)
        → SPEAK_TEXT bounded output

It does NOT:
  - import or touch services/discord_bot.py
  - own a Discord client / event loop / bot lifecycle
  - attempt a real voice connection (deferred to a later pass)
  - parse freeform commands
  - widen any trust boundary

The adapter runs in TRANSCRIPT-ONLY mode by default. A live
`discord.VoiceClient` can OPTIONALLY be attached via
`attach_voice_client(vc)`, which switches the adapter into ATTACHED mode
and enables bounded TTS playback through `eos_ai.substrate.discord_voice_playback`.

Modes
-----
- TRANSCRIPT_ONLY (default): no live voice connection. The adapter is a
  pure façade over `transcript_inject.inject_transcript`. Safe everywhere.
- ATTACHED: a live `discord.VoiceClient` is attached via
  `attach_voice_client(vc)`. EOS reply text generated by the responder
  is rendered through `VoiceEngine.speak()` and played into the channel
  via `vc.play(FFmpegPCMAudio(...))`. Playback is bounded (one item at a
  time), observable (history ring + status_report), and degrades safely
  if any dependency is missing.
- DEGRADED: a VC was attached but playback prerequisites are missing
  (no ffmpeg, no TTS, no voice extras). Transcript ingestion still works.

Optional opt-in hook
--------------------
`services/discord_bot.py` calls `inject_utterance(...)` from inside its
existing Groq-STT callback ONLY when the env var
`EOS_DISCORD_VOICE_TRANSPORT_ENABLED` is truthy. The default is OFF, so
existing Discord behavior is unchanged.
"""

from __future__ import annotations

import os
import sys
import threading
from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from typing import Any, Optional


def _log(msg: str) -> None:
    print(f"[substrate.discord_voice_transport] {msg}", file=sys.stderr)


def _utcnow_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


# ─── Capability probe ────────────────────────────────────────────────────────


def _probe_discord_capability() -> dict[str, Any]:
    """Lazy, side-effect-free probe of the discord.py / py-cord library.

    NEVER imports services.discord_bot or starts any client.
    """
    out: dict[str, Any] = {
        "discord_lib_present": False,
        "discord_lib_version": None,
        "voice_extras_present": False,
        "ffmpeg_assumed_present": False,
    }
    try:
        import discord  # type: ignore  # noqa: F401

        out["discord_lib_present"] = True
        out["discord_lib_version"] = getattr(discord, "__version__", None)
        try:
            from discord import VoiceClient  # type: ignore  # noqa: F401

            out["voice_extras_present"] = True
        except Exception:
            out["voice_extras_present"] = False
    except Exception:
        out["discord_lib_present"] = False
    # ffmpeg presence is best-effort: we don't shell out, just trust env.
    out["ffmpeg_assumed_present"] = bool(os.getenv("PATH"))
    return out


# ─── Models ──────────────────────────────────────────────────────────────────


@dataclass
class DiscordTransportEvent:
    """One bounded transcript event flowing through the transport."""

    node_id: str
    text: str
    inject_status: str
    session_id: Optional[str] = None
    role_slug: Optional[str] = None
    user_id: Optional[str] = None
    guild_id: Optional[str] = None
    channel_id: Optional[str] = None
    occurred_at: str = field(default_factory=_utcnow_iso)
    detail: str = ""
    metadata: dict = field(default_factory=dict)

    def as_dict(self) -> dict[str, Any]:
        return asdict(self)


# ─── Bounded transport history ───────────────────────────────────────────────


_HISTORY_CAP = 50


class _TransportHistory:
    def __init__(self, cap: int = _HISTORY_CAP) -> None:
        self._lock = threading.RLock()
        self._rows: list[DiscordTransportEvent] = []
        self._cap = cap

    def record(self, ev: DiscordTransportEvent) -> DiscordTransportEvent:
        with self._lock:
            self._rows.append(ev)
            if len(self._rows) > self._cap:
                drop = len(self._rows) - self._cap
                self._rows = self._rows[drop:]
        return ev

    def latest(
        self, limit: int = 10, node_id: Optional[str] = None
    ) -> list[DiscordTransportEvent]:
        with self._lock:
            rows = list(self._rows)
        if node_id is not None:
            rows = [r for r in rows if r.node_id == node_id]
        rows.sort(key=lambda r: r.occurred_at or "", reverse=True)
        return rows[: max(0, int(limit))]

    def clear(self) -> None:
        with self._lock:
            self._rows.clear()


_history_singleton: Optional[_TransportHistory] = None
_history_singleton_lock = threading.Lock()


def get_transport_history() -> _TransportHistory:
    global _history_singleton
    if _history_singleton is None:
        with _history_singleton_lock:
            if _history_singleton is None:
                _history_singleton = _TransportHistory()
    return _history_singleton


def reset_transport_history_for_tests() -> None:
    global _history_singleton
    with _history_singleton_lock:
        _history_singleton = None


# ─── Transport adapter ───────────────────────────────────────────────────────


def _build_node_id(guild_id: Optional[str], channel_id: Optional[str]) -> str:
    if guild_id and channel_id:
        return f"discord_vc_{guild_id}_{channel_id}"
    if guild_id:
        return f"discord_vc_{guild_id}"
    return "discord_transport_default"


class DiscordVoiceTransport:
    """Pure adapter from a Discord voice surface to the bounded voice loop.

    Construction is cheap: no network, no event loop, no client. The adapter
    is safe to instantiate from any process (operator CLI, smoke test,
    `services/discord_bot.py` opt-in hook).
    """

    def __init__(
        self,
        *,
        guild_id: Optional[str] = None,
        channel_id: Optional[str] = None,
        node_id: Optional[str] = None,
        role_slug: str = "ea_orchestrator",
        ensure_node: bool = True,
    ) -> None:
        self.guild_id = str(guild_id) if guild_id is not None else None
        self.channel_id = str(channel_id) if channel_id is not None else None
        self.node_id = node_id or _build_node_id(self.guild_id, self.channel_id)
        self.role_slug = role_slug
        self._mode = "transcript_only"
        self._playback_enabled = False
        self._attached_vc = None  # holds a discord.VoiceClient or test fake
        # Bounded playback adapter — created lazily on first attach so
        # transcript-only mode never imports voice_engine / ffmpeg probes.
        self._playback = None  # type: Optional[Any]
        if ensure_node:
            self._ensure_node_registered()

    # ── Optional VoiceClient attachment ────────────────────────────────────

    def _ensure_playback(self):
        if self._playback is None:
            from eos_ai.substrate.discord_voice_playback import (
                DiscordVoicePlayback,
            )

            self._playback = DiscordVoicePlayback(node_id=self.node_id)
        return self._playback

    def attach_voice_client(
        self, voice_client: Any, *, enabled: bool = True
    ) -> dict[str, Any]:
        """Attach a real (or fake) Discord VoiceClient to this transport.

        Switches the transport mode to ATTACHED and enables bounded
        playback by default. Safe to call multiple times — re-attachment
        replaces the previous VC.

        Never raises. Returns a JSON-friendly dict describing the new state.
        """
        try:
            playback = self._ensure_playback()
            playback.attach(voice_client, enabled=enabled)
            self._attached_vc = voice_client
            self._playback_enabled = bool(enabled)
            self._mode = "attached"
            return {
                "status": "attached",
                "playback_enabled": self._playback_enabled,
                "node_id": self.node_id,
            }
        except Exception as e:  # noqa: BLE001
            _log(f"attach_voice_client failed: {e}")
            return {"status": "attach_failed", "detail": str(e)}

    def detach_voice_client(self) -> dict[str, Any]:
        """Drop any attached VoiceClient and return to transcript-only mode."""
        try:
            if self._playback is not None:
                self._playback.detach()
            self._attached_vc = None
            self._playback_enabled = False
            self._mode = "transcript_only"
            return {"status": "detached", "node_id": self.node_id}
        except Exception as e:  # noqa: BLE001
            return {"status": "detach_failed", "detail": str(e)}

    def set_playback_enabled(self, enabled: bool) -> dict[str, Any]:
        """Toggle playback on/off without dropping the attached VC."""
        self._playback_enabled = bool(enabled)
        if self._playback is not None:
            self._playback.set_enabled(self._playback_enabled)
        return {
            "status": "ok",
            "playback_enabled": self._playback_enabled,
            "attached": self._attached_vc is not None,
        }

    def play_reply(self, text: str) -> dict[str, Any]:
        """Bounded playback entry point for an EOS reply.

        Always returns a JSON-friendly dict. If no VC is attached or
        playback is disabled, returns a structured `disabled` result
        instead of raising.
        """
        if self._playback is None or not self._playback_enabled:
            return {
                "status": "disabled",
                "detail": "no voice client attached or playback disabled",
            }
        try:
            return self._playback.play_text(text).as_dict()
        except Exception as e:  # noqa: BLE001
            return {"status": "playback_error", "detail": str(e)}

    # ── Node registration (best-effort, never raises) ──────────────────────

    def _ensure_node_registered(self) -> None:
        """Register the discord-side node so VoiceSessionRuntime accepts it.

        VoiceSessionRuntime.start_session validates `node_id` against
        NodeRegistry. Without this, every transport call would land in an
        ERROR session. We register a LOCAL_STATION node with capabilities
        describing the bounded transport — exactly the same posture
        StationDaemon uses for the workstation node.
        """
        try:
            from eos_ai.substrate.nodes import (
                Node,
                NodeRegistry,
                NodeStatus,
                NodeType,
            )

            reg = NodeRegistry.default()
            existing = reg.get(self.node_id)
            if existing is not None:
                return
            reg.upsert(
                Node(
                    node_id=self.node_id,
                    node_type=NodeType.LOCAL_STATION,
                    capabilities=["voice_transport", "transcript_inject"],
                    status=NodeStatus.ONLINE,
                    availability="on_demand",
                    metadata={
                        "transport": "discord",
                        "guild_id": self.guild_id,
                        "channel_id": self.channel_id,
                    },
                )
            )
        except Exception as e:  # noqa: BLE001
            _log(f"node registration failed for {self.node_id}: {e}")

    # ── Lifecycle (thin wrappers — no parallel pipeline) ───────────────────

    def start_session(self, role_slug: Optional[str] = None) -> dict[str, Any]:
        """Start (or resume) a bounded voice session for this transport node."""
        try:
            from eos_ai.substrate.voice_session import (
                VoiceSessionRuntime,
                get_voice_session_store,
            )
        except Exception as e:  # noqa: BLE001
            return {"status": "import_failed", "detail": str(e)}

        role = role_slug or self.role_slug
        store = get_voice_session_store()
        active = store.active(node_id=self.node_id)
        if active:
            s = active[0]
            return {
                "status": "resumed",
                "session_id": s.session_id,
                "role_slug": s.role_slug,
            }
        runtime = VoiceSessionRuntime()
        try:
            session = runtime.start_session(
                self.node_id,
                role_slug=role,
                metadata={
                    "started_by": "discord_voice_transport",
                    "transport": "discord",
                    "guild_id": self.guild_id,
                    "channel_id": self.channel_id,
                },
            )
        except Exception as e:  # noqa: BLE001
            return {"status": "start_failed", "detail": str(e)}
        return {
            "status": session.status.value,
            "session_id": session.session_id,
            "role_slug": session.role_slug,
            "error_reason": session.error_reason,
        }

    def end_session(self, *, reason: Optional[str] = None) -> dict[str, Any]:
        try:
            from eos_ai.substrate.voice_session import (
                VoiceSessionRuntime,
                get_voice_session_store,
            )
        except Exception as e:  # noqa: BLE001
            return {"status": "import_failed", "detail": str(e)}
        store = get_voice_session_store()
        active = store.active(node_id=self.node_id)
        if not active:
            return {"status": "no_active_session"}
        runtime = VoiceSessionRuntime()
        ended = runtime.end_session(
            active[0].session_id,
            reason=reason or "discord_voice_transport.end_session",
        )
        if ended is None:
            return {"status": "end_failed"}
        return {
            "status": ended.status.value,
            "session_id": ended.session_id,
            "ended_at": ended.ended_at,
        }

    # ── Core: transcript ingestion ─────────────────────────────────────────

    def inject_utterance(
        self,
        text: str,
        *,
        user_id: Optional[str] = None,
        role_slug: Optional[str] = None,
        metadata: Optional[dict] = None,
    ) -> dict[str, Any]:
        """Bounded entry point. Mirrors transcript_inject.inject_transcript()
        with `source="discord_voice"` and discord-shaped metadata.

        Never raises. Always returns a JSON-friendly dict.
        """
        clean = (text or "").strip()
        meta = {
            "transport": "discord",
            "guild_id": self.guild_id,
            "channel_id": self.channel_id,
            "user_id": str(user_id) if user_id is not None else None,
            **(metadata or {}),
        }

        if not clean:
            ev = DiscordTransportEvent(
                node_id=self.node_id,
                text="",
                inject_status="empty_text",
                user_id=meta.get("user_id"),
                guild_id=self.guild_id,
                channel_id=self.channel_id,
                detail="empty text",
                metadata=meta,
            )
            get_transport_history().record(ev)
            return {"status": "empty_text", "event": ev.as_dict()}

        try:
            from eos_ai.substrate.transcript_inject import inject_transcript
        except Exception as e:  # noqa: BLE001
            return {"status": "import_failed", "detail": str(e)}

        try:
            result = inject_transcript(
                self.node_id,
                clean,
                source="discord_voice",
                start_if_missing=True,
                role_slug=role_slug or self.role_slug,
                metadata=meta,
            )
        except Exception as e:  # noqa: BLE001
            ev = DiscordTransportEvent(
                node_id=self.node_id,
                text=clean,
                inject_status="exception",
                user_id=meta.get("user_id"),
                guild_id=self.guild_id,
                channel_id=self.channel_id,
                detail=f"inject_transcript raised: {e}",
                metadata=meta,
            )
            get_transport_history().record(ev)
            return {"status": "exception", "detail": str(e), "event": ev.as_dict()}

        ev = DiscordTransportEvent(
            node_id=self.node_id,
            text=clean,
            inject_status=result.get("status", "unknown"),
            session_id=result.get("session_id"),
            role_slug=result.get("role_slug"),
            user_id=meta.get("user_id"),
            guild_id=self.guild_id,
            channel_id=self.channel_id,
            detail=result.get("detail", ""),
            metadata=meta,
        )
        get_transport_history().record(ev)

        # Bounded auto-playback: if a VoiceClient is attached AND playback
        # is enabled, render the latest AGENT turn through the playback
        # adapter. Failures NEVER raise — they degrade to a structured
        # `playback` field in the return dict so callers can observe them.
        playback_outcome: Optional[dict] = None
        if self._playback_enabled and self._playback is not None:
            try:
                reply_text = self._latest_agent_reply(result.get("session_id"))
                if reply_text:
                    playback_outcome = self._playback.play_text(reply_text).as_dict()
                else:
                    playback_outcome = {
                        "status": "no_reply",
                        "detail": "no agent turn produced",
                    }
            except Exception as e:  # noqa: BLE001
                playback_outcome = {"status": "playback_error", "detail": str(e)}

        return {
            "status": result.get("status"),
            "session_id": result.get("session_id"),
            "role_slug": result.get("role_slug"),
            "detail": result.get("detail"),
            "audio_loop": result.get("audio_loop"),
            "event": ev.as_dict(),
            "playback": playback_outcome,
        }

    def _latest_agent_reply(self, session_id: Optional[str]) -> Optional[str]:
        """Best-effort: return the most recent AGENT turn text for `session_id`."""
        if not session_id:
            return None
        try:
            from eos_ai.substrate.voice_session import (
                VoiceTurnSource,
                get_voice_session_store,
            )

            session = get_voice_session_store().get(session_id)
            if session is None:
                return None
            for turn in reversed(session.turns):
                if turn.source == VoiceTurnSource.AGENT and (turn.text or "").strip():
                    return turn.text
        except Exception as e:  # noqa: BLE001
            _log(f"_latest_agent_reply failed: {e}")
        return None

    # ── Reporting ──────────────────────────────────────────────────────────

    def _build_playback_status(self, mode: str) -> dict[str, Any]:
        """Build shared PlaybackStatusSnapshot dict for this transport."""
        try:
            if self._playback is not None:
                snap = self._playback.playback_status_snapshot()
                if isinstance(snap, dict):
                    snap["mode"] = mode
                return snap
            from eos_ai.substrate.playback_status import (
                make_playback_status_snapshot,
            )

            return make_playback_status_snapshot(
                transport="discord",
                mode=mode,
                attached=False,
                enabled=False,
            ).as_dict()
        except Exception as e:  # noqa: BLE001
            _log(f"_build_playback_status failed: {e}")
            return {
                "transport": "discord",
                "mode": mode,
                "attached": False,
                "enabled": False,
                "busy": False,
                "depth": 0,
                "max_depth": 1,
                "attempt_count": 0,
                "by_status": {},
                "last_result": None,
                "recent": [],
            }

    def status_report(self, *, history_limit: int = 10) -> dict[str, Any]:
        """Bounded snapshot of transport mode + capability + recent events."""
        capability = _probe_discord_capability()

        # Voice session counts for this node (best-effort).
        active_count = 0
        recent_sessions: list[dict] = []
        try:
            from eos_ai.substrate.voice_session import get_voice_session_store

            store = get_voice_session_store()
            active_count = len(store.active(node_id=self.node_id))
            recent_sessions = [
                s.as_dict() for s in store.latest(limit=5, node_id=self.node_id)
            ]
        except Exception as e:  # noqa: BLE001
            _log(f"voice_session_store lookup failed: {e}")

        # Audio loop snapshot for this node (best-effort).
        audio_loop: Optional[dict] = None
        try:
            from eos_ai.substrate.result_query import audio_loop_snapshot

            audio_loop = audio_loop_snapshot(node_id=self.node_id)
        except Exception as e:  # noqa: BLE001
            _log(f"audio_loop_snapshot failed: {e}")

        recent_events = [
            e.as_dict()
            for e in get_transport_history().latest(
                limit=history_limit, node_id=self.node_id
            )
        ]

        # Playback snapshot (only if a playback adapter has been created).
        playback_snapshot: Optional[dict] = None
        playback_capability: Optional[dict] = None
        playback_recent: list[dict] = []
        if self._playback is not None:
            try:
                playback_snapshot = self._playback.snapshot()
            except Exception as e:  # noqa: BLE001
                _log(f"playback snapshot failed: {e}")
            try:
                from eos_ai.substrate.discord_voice_playback import (
                    get_playback_history,
                    probe_playback_capability,
                )

                playback_capability = probe_playback_capability()
                playback_recent = [
                    r.as_dict()
                    for r in get_playback_history().latest(
                        limit=history_limit, node_id=self.node_id
                    )
                ]
            except Exception as e:  # noqa: BLE001
                _log(f"playback history lookup failed: {e}")

        # Mode classification.
        if self._attached_vc is not None:
            if (
                playback_capability
                and playback_capability.get("voice_extras_present")
                and playback_capability.get("ffmpeg_present")
                and playback_capability.get("voice_engine_importable")
                and self._playback_enabled
            ):
                mode = "attached"
            else:
                mode = "attached_degraded"
        elif not capability["discord_lib_present"]:
            mode = "transcript_only_no_lib"
        else:
            mode = "transcript_only"

        return {
            "node_id": self.node_id,
            "guild_id": self.guild_id,
            "channel_id": self.channel_id,
            "role_slug": self.role_slug,
            "mode": mode,
            "playback_enabled": self._playback_enabled,
            "attached_vc": self._attached_vc is not None,
            "capability": capability,
            "active_session_count": active_count,
            "recent_sessions": recent_sessions,
            "recent_events": recent_events,
            "audio_loop": audio_loop,
            "playback": playback_snapshot,
            "playback_capability": playback_capability,
            "recent_playback": playback_recent,
            "playback_status": self._build_playback_status(mode),
            "env_hook_enabled": _env_hook_enabled(),
            "playback_env_enabled": _playback_env_enabled(),
            "generated_at": _utcnow_iso(),
        }


# ─── Default singleton (keyed by guild/channel) ──────────────────────────────


_default_lock = threading.Lock()
_default_transports: dict[tuple, DiscordVoiceTransport] = {}


def get_default_discord_voice_transport(
    *,
    guild_id: Optional[str] = None,
    channel_id: Optional[str] = None,
    role_slug: str = "ea_orchestrator",
) -> DiscordVoiceTransport:
    """Return (or lazily create) a default transport for (guild, channel).

    The adapter is intentionally cheap to construct, but operators usually
    want one stable instance per voice channel for transport history coherence.
    """
    key = (str(guild_id) if guild_id else None, str(channel_id) if channel_id else None)
    with _default_lock:
        existing = _default_transports.get(key)
        if existing is not None:
            return existing
        t = DiscordVoiceTransport(
            guild_id=guild_id,
            channel_id=channel_id,
            role_slug=role_slug,
        )
        _default_transports[key] = t
        return t


def reset_default_discord_voice_transports_for_tests() -> None:
    with _default_lock:
        _default_transports.clear()


# ─── Env-gated opt-in hook ───────────────────────────────────────────────────


_ENV_HOOK_VAR = "EOS_DISCORD_VOICE_TRANSPORT_ENABLED"
_PLAYBACK_ENV_VAR = "EOS_DISCORD_VOICE_PLAYBACK_ENABLED"


def _env_hook_enabled() -> bool:
    val = os.getenv(_ENV_HOOK_VAR, "").strip().lower()
    return val in ("1", "true", "yes", "on")


def _playback_env_enabled() -> bool:
    val = os.getenv(_PLAYBACK_ENV_VAR, "").strip().lower()
    return val in ("1", "true", "yes", "on")


def maybe_attach_discord_voice_client(
    voice_client: Any,
    *,
    guild_id: Optional[Any] = None,
    channel_id: Optional[Any] = None,
    role_slug: str = "ea_orchestrator",
) -> Optional[dict[str, Any]]:
    """Opt-in helper for `services/discord_bot.py` to attach a real VC.

    Returns None when EOS_DISCORD_VOICE_PLAYBACK_ENABLED is not truthy
    (DEFAULT — current bot behavior unchanged). When enabled, attaches
    `voice_client` to the default transport for (guild, channel).

    Never raises. Safe to call from any callback.
    """
    if not _playback_env_enabled():
        return None
    if voice_client is None:
        return {"status": "no_voice_client"}
    try:
        transport = get_default_discord_voice_transport(
            guild_id=guild_id,
            channel_id=channel_id,
            role_slug=role_slug,
        )
        return transport.attach_voice_client(voice_client, enabled=True)
    except Exception as e:  # noqa: BLE001
        _log(f"maybe_attach_discord_voice_client failed: {e}")
        return {"status": "attach_failed", "detail": str(e)}


def maybe_mirror_discord_utterance(
    text: str,
    *,
    user_id: Optional[Any] = None,
    guild_id: Optional[Any] = None,
    channel_id: Optional[Any] = None,
    role_slug: str = "ea_orchestrator",
    voice_client: Any = None,
) -> Optional[dict[str, Any]]:
    """Opt-in mirror hook for `services/discord_bot.py`.

    Behavior:
      - Returns `None` immediately if EOS_DISCORD_VOICE_TRANSPORT_ENABLED is
        not truthy. This is the DEFAULT — existing Discord behavior unchanged.
      - When enabled, calls `get_default_discord_voice_transport(...)` and
        injects the utterance via the bounded seam.
      - Never raises — failures log and return a status dict.

    Existing Discord routing (gateway / TTS) is NOT replaced. This is purely
    a parallel mirror onto the substrate so transcripts also flow through
    the same `inject_transcript → voice_session → responder → SPEAK_TEXT`
    chain that the local PTT path uses.
    """
    if not _env_hook_enabled():
        return None
    try:
        transport = get_default_discord_voice_transport(
            guild_id=guild_id,
            channel_id=channel_id,
            role_slug=role_slug,
        )
        # If the caller passed a VoiceClient AND playback is env-enabled,
        # opportunistically attach it before injecting so the responder's
        # reply can be played back in the same call.
        if voice_client is not None and _playback_env_enabled():
            try:
                transport.attach_voice_client(voice_client, enabled=True)
            except Exception as e:  # noqa: BLE001
                _log(f"opportunistic attach failed: {e}")
        return transport.inject_utterance(text, user_id=user_id)
    except Exception as e:  # noqa: BLE001
        _log(f"maybe_mirror_discord_utterance failed: {e}")
        return {"status": "mirror_failed", "detail": str(e)}


__all__ = [
    "DiscordVoiceTransport",
    "DiscordTransportEvent",
    "get_default_discord_voice_transport",
    "reset_default_discord_voice_transports_for_tests",
    "get_transport_history",
    "reset_transport_history_for_tests",
    "maybe_mirror_discord_utterance",
    "maybe_attach_discord_voice_client",
]
