"""Generate the candidate stack's env file by ALLOWLIST.

The Wave-1 candidate container must run with the SMALLEST env surface that lets
cockpit auth + planning-LLM enhancement work — and nothing else. Mesh secrets,
Discord tokens, Fly tokens, GitHub tokens, and every other credential in the
production `services/.env` are DELIBERATELY OMITTED so a candidate deploy can
never actuate a remote node, post to Discord, deploy, or push.

The allowlist was derived by reading:
  * transports/api/cockpit_auth.py — Clerk JWT server-side validation uses ONLY
    CLERK_JWKS_URL + ALLOWED_CLERK_USER_IDS (JWKS = public keys; no secret key
    needed server-side). Optional dev knobs: UMH_DEV_BYPASS, UMH_DOCKER_BRIDGE_IP
    (both omitted by default — candidate runs credential-first, no bypass).
  * adapters/models/model_router.py — planning LLM enhancement reads
    ANTHROPIC_API_KEY, GEMINI_API_KEY, GROQ_API_KEY (config.api_key_env). These
    let the deterministic plan be AI-enhanced; without them the deterministic
    spine still produces a plan (Deterministic-First Principle).

Everything else is omitted. UMH_* candidate vars are injected explicitly by the
dispatcher (UMH_STATE_DIR, UMH_BUILD_COMMIT, PYTHONDONTWRITEBYTECODE), not read
from production env.

Emits an audit JSON listing the INCLUDED KEY NAMES ONLY (never values) so a test
can assert no mesh / Discord / Fly / GitHub key leaked into the candidate stack.
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path

# Auth: exactly what cockpit_auth.py reads to validate Clerk JWTs.
_AUTH_KEYS = (
    "CLERK_JWKS_URL",
    "ALLOWED_CLERK_USER_IDS",
)

# Planning LLM enhancement: model_router.py api_key_env names in the fallback
# chain. Omitting them is safe (deterministic fallback) but degrades plan
# quality, so they are allowlisted.
_LLM_KEYS = (
    "ANTHROPIC_API_KEY",
    "GEMINI_API_KEY",
    "GROQ_API_KEY",
)

# The full allowlist. A key is included ONLY if it is present (non-empty) in the
# source env — absent keys are silently skipped, never emitted blank.
ALLOWLIST: tuple[str, ...] = _AUTH_KEYS + _LLM_KEYS

# Patterns that must NEVER appear in the candidate env (defense-in-depth: even
# if the allowlist were widened by mistake, these are hard-denied).
_DENY_SUBSTRINGS = (
    "MESH",
    "DISCORD",
    "FLY",
    "GITHUB",
    "GH_",
    "NOTION",
    "TELEGRAM",
    "APIFY",
    "DATABASE_URL",
    "SSH",
    "PRIVATE",
    "1PASSWORD",
    "OP_",
)


def _parse_env_file(path: Path) -> dict[str, str]:
    """Minimal .env parser — KEY=VALUE lines, ignores comments/blanks."""
    env: dict[str, str] = {}
    if not path.exists():
        return env
    for raw in path.read_text(encoding="utf-8", errors="replace").splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, val = line.partition("=")
        key = key.strip()
        # Strip surrounding quotes on the value only.
        val = val.strip().strip('"').strip("'")
        if key:
            env[key] = val
    return env


def _is_denied(key: str) -> bool:
    up = key.upper()
    return any(sub in up for sub in _DENY_SUBSTRINGS)


def build_candidate_env(
    source_env: Path,
    *,
    extra_umh: dict[str, str] | None = None,
) -> tuple[dict[str, str], dict[str, list[str]]]:
    """Return (candidate_env, audit).

    candidate_env: the allowlisted KEY=VALUE map to write.
    audit: {"included": [...names...], "skipped_absent": [...], "denied": [...]}.
    """
    src = _parse_env_file(source_env)
    included: dict[str, str] = {}
    audit: dict[str, list[str]] = {"included": [], "skipped_absent": [], "denied": []}

    for key in ALLOWLIST:
        if _is_denied(key):
            # Should never happen (allowlist is curated), but fail-closed.
            audit["denied"].append(key)
            continue
        val = src.get(key, "").strip()
        if val:
            included[key] = val
            audit["included"].append(key)
        else:
            audit["skipped_absent"].append(key)

    # Explicit candidate-only UMH_* vars — provided by the dispatcher, not env.
    for k, v in (extra_umh or {}).items():
        if _is_denied(k):
            audit["denied"].append(k)
            continue
        included[k] = v
        audit["included"].append(k)

    return included, audit


def render_env_file(env: dict[str, str]) -> str:
    """Render KEY=VALUE lines with a provenance header (no values in comments)."""
    header = (
        "# Wave-1 candidate env — generated by infra/candidate/make_candidate_env.py\n"
        "# ALLOWLIST ONLY. Mesh/Discord/Fly/GitHub/DB secrets deliberately omitted.\n"
        "# Do not commit. Do not add keys here by hand — widen the allowlist with a\n"
        "# reason instead.\n"
    )
    body = "\n".join(f"{k}={v}" for k, v in env.items())
    return header + body + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate the Wave-1 candidate env by allowlist")
    parser.add_argument(
        "--source",
        default=os.path.join(os.environ.get("UMH_ROOT", "/opt/OS"), "services", ".env"),
        help="Source production env file",
    )
    parser.add_argument("--out", required=True, help="Output candidate.env path")
    parser.add_argument("--audit-out", default="", help="Optional audit JSON path")
    parser.add_argument("--state-dir", default="/state/umh")
    parser.add_argument("--build-commit", default="")
    parser.add_argument(
        "--dry-run", action="store_true", help="Print audit + would-write path, write nothing"
    )
    args = parser.parse_args(argv)

    extra_umh = {
        "UMH_STATE_DIR": args.state_dir,
        "PYTHONDONTWRITEBYTECODE": "1",
    }
    if args.build_commit:
        extra_umh["UMH_BUILD_COMMIT"] = args.build_commit

    env, audit = build_candidate_env(Path(args.source), extra_umh=extra_umh)

    if args.dry_run:
        print(json.dumps({"would_write": args.out, "audit": audit}, indent=2))
        return 0

    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(render_env_file(env), encoding="utf-8")
    try:
        os.chmod(out_path, 0o600)
    except OSError:
        pass

    if args.audit_out:
        Path(args.audit_out).write_text(json.dumps(audit, indent=2), encoding="utf-8")

    # Names only — never values.
    print(json.dumps({"written": str(out_path), "audit": audit}, indent=2))
    return 0


if __name__ == "__main__":
    sys.exit(main())
