"""
DecisionTrace — compatibility shim.

Canonical location: umh/decision/trace.py
This module re-exports UMH types and provides the build_trace() factory
which depends on EOS runtime state (strategy_memory singleton).

All existing imports from umh.runtime_engine.decision_trace continue to work.
"""

from __future__ import annotations

from umh.decision.trace import (  # noqa: F401
    DEBUG_TRACE,
    MAX_TRACES,
    DecisionTrace,
    debug_print,
)


def build_trace(
    turn_id: int,
    evaluation: dict | None = None,
    signals: object | None = None,
    result: object | None = None,
    directives: list[str] | None = None,
    control_decision: object | None = None,
    thresholds_used: dict | None = None,
    strategy_selection: dict | None = None,
    synthesized_strategy: str | None = None,
    synthesis_reason: str | None = None,
    goal_mode: str | None = None,
    convergence_status: str | None = None,
    convergence_reason: str | None = None,
    convergence_action: str | None = None,
    unified_influence: dict | None = None,
    goal_score: float | None = None,
    goal_delta: float | None = None,
    goal_confidence: float | None = None,
    exploration_enabled: bool | None = None,
    synthesis_enabled: bool | None = None,
    goal_gating_reason: str | None = None,
    active_goal_id: str | None = None,
    goal_pool_snapshot: dict | None = None,
    blended_goals: tuple[tuple[str, float], ...] | None = None,
    blended_primary_goal_id: str | None = None,
    blended_entropy: float | None = None,
    execution_budget: dict | None = None,
    candidate_distribution: dict | None = None,
    memory_persisted: bool | None = None,
    memory_version: int | None = None,
    persistence_loaded: bool | None = None,
    persistence_saved: bool | None = None,
    persistence_version: int | None = None,
    persisted_components: tuple[str, ...] | None = None,
    persistence_error: str | None = None,
    outcome_attached: bool | None = None,
    outcome_score: float | None = None,
    attribution_weights: dict | None = None,
    attribution_reason: str | None = None,
    exploration_rate: float | None = None,
    exploration_reason: str | None = None,
    det_exploration_active: bool | None = None,
    det_exploration_adjustments: dict | None = None,
    generated_goals: tuple[dict, ...] | None = None,
    goal_mutations: tuple[dict, ...] | None = None,
    meta_goal_reason: str | None = None,
    goal_validation_results: tuple[dict, ...] | None = None,
    rejected_goals: tuple[str, ...] | None = None,
    validation_reason: str | None = None,
    goal_alignment_scores: dict | None = None,
    alignment_penalties: tuple[str, ...] | None = None,
    alignment_decisions: tuple[dict, ...] | None = None,
    counterfactual_expected_utility: dict | None = None,
    counterfactual_confidence: dict | None = None,
    counterfactual_reasoning: dict | None = None,
    counterfactual_uncertainty: dict | None = None,
    counterfactual_exploration_boost: dict | None = None,
    counterfactual_horizon_value: dict | None = None,
    counterfactual_horizon_reason: dict | None = None,
    persistence_streaks: dict | None = None,
    commitment_bonuses: dict | None = None,
    switch_penalty_applied: bool | None = None,
    strategy_mutations: "tuple[dict, ...] | None" = None,
    strategy_origins: dict | None = None,
    mutation_reason: str | None = None,
    active_plan_id: str | None = None,
    active_plan_step: str | None = None,
    plan_confidence: float | None = None,
    plan_count: int | None = None,
    plan_generation_reason: str | None = None,
    world_state_id: str | None = None,
    world_state_cluster: str | None = None,
    world_state_similarity: float | None = None,
    conditioning_bias: dict | None = None,
    strategy_base_scores: dict | None = None,
    strategy_conditioned_scores: dict | None = None,
    plan_step_goal_id: str | None = None,
    plan_step_attributed_score: float | None = None,
    plan_step_attribution_source: str | None = None,
    plan_step_status: str | None = None,
    plan_step_retry_count: int | None = None,
    plan_step_failure_streak: int | None = None,
    state_transfer_weight: float | None = None,
    strategy_transfer_scores: dict | None = None,
    plan_transfer_score: float | None = None,
    state_similarity_used: float | None = None,
    replan_adjustment: float | None = None,
    plan_mutation_applied: bool | None = None,
    plan_mutation_type: str | None = None,
    mutated_plan_id: str | None = None,
    mutated_from_plan_id: str | None = None,
    plan_recombination_applied: bool | None = None,
    recombined_plan_id: str | None = None,
    recombined_from_plan_ids: tuple[str, ...] | None = None,
    plan_evolution_reason: str | None = None,
    plan_origin_snapshot: dict | None = None,
    world_state_cluster_quality: float | None = None,
    learned_state_bias: dict | None = None,
    combined_state_bias: dict | None = None,
    cluster_quality_ema: float | None = None,
    cluster_observation_count: int | None = None,
    world_state_reinforcement_applied: bool | None = None,
    influence_components: "tuple[dict, ...] | None" = None,
    influence_weights: dict | None = None,
    final_influence_score: float | None = None,
    influence_breakdown: dict | None = None,
    influence_applied: bool | None = None,
    influence_adjustment: float | None = None,
    influence_pre_score: float | None = None,
    influence_post_score: float | None = None,
    meta_weights: dict | None = None,
    meta_weight_adjustments: dict | None = None,
    meta_weight_signal_performance: dict | None = None,
    active_policy: str | None = None,
    policy_reason: str | None = None,
    policy_adjustments: dict | None = None,
    active_directives: "tuple[dict, ...] | None" = None,
    directive_scores: dict | None = None,
    directive_selection_reason: str | None = None,
    directive_evolution_events: "tuple[str, ...] | None" = None,
    memory_entries_written: "tuple[str, ...] | None" = None,
    memory_queries_used: "tuple[str, ...] | None" = None,
    memory_aggregation_summary: dict | None = None,
    fabric_analytics_summary: dict | None = None,
    analytics_signal: dict | None = None,
    analytics_applied: bool | None = None,
    objective_snapshot: dict | None = None,
    objective_value: float | None = None,
    objective_trend: str | None = None,
    optimization_signal: dict | None = None,
    objective_history_length: int | None = None,
    objective_persisted: bool | None = None,
    objective_decision_signal: dict | None = None,
    trap_signal_active: bool | None = None,
    trap_adjustment: float | None = None,
    restart_state_loaded: bool | None = None,
    meta_signal_strength: float | None = None,
    stability_guard_active: bool | None = None,
    context_signal: dict | None = None,
    context_type: str | None = None,
    meta_generalization_matched: bool | None = None,
    meta_generalization_prototype_id: int | None = None,
    meta_generalization_similarity: float | None = None,
    meta_generalization_priors: dict | None = None,
    meta_generalization_signature: dict | None = None,
    meta_generalization_prototype_usage: int | None = None,
    meta_generalization_prototype_avg_reward: float | None = None,
    meta_generalization_suppressed: bool | None = None,
    causal_signal: dict | None = None,
    causal_confidence: float | None = None,
    causal_applied: bool | None = None,
    causal_context_match: str | None = None,
    causal_credit: dict | None = None,
    immediate_credit: dict | None = None,
    delayed_credit: dict | None = None,
    structural_credit: dict | None = None,
    credit_reason: str | None = None,
    credited_entities: dict | None = None,
    credit_signal: dict | None = None,
    credit_confidence: float | None = None,
    credit_applied: bool | None = None,
    credit_horizon: int | None = None,
    foresight_signal: dict | None = None,
    foresight_confidence: float | None = None,
    foresight_applied: bool | None = None,
    foresight_depth: int | None = None,
    orchestration_consensus: float | None = None,
    orchestration_active_count: int | None = None,
    orchestration_suppressed_count: int | None = None,
    orchestration_dominant_source: str | None = None,
    sensitivity_factor: float | None = None,
    sensitivity_reason: str | None = None,
    sensitivity_applied: bool | None = None,
    planner_active: bool | None = None,
    planner_scores: dict | None = None,
    planner_choice: str | None = None,
    planner_confidence: float | None = None,
    planner_reason: str | None = None,
    planner_horizon: int | None = None,
    planner_uncertainty: float | None = None,
    planner_consistency: float | None = None,
    planner_adjusted_confidence: float | None = None,
    world_snapshot_version: int | None = None,
    world_observation_count: int | None = None,
    world_entity_count: int | None = None,
    world_relation_count: int | None = None,
    ingested_signal_count: int | None = None,
    ingested_signal_sources: "tuple[str, ...] | None" = None,
    world_derived_count: int | None = None,
    world_global_flags: "tuple[str, ...] | None" = None,
    world_riskiest_entity: str | None = None,
    world_riskiest_entity_health: str | None = None,
    world_volatile_entity_count: int | None = None,
    world_bad_entity_count: int | None = None,
    simulation_ran: bool | None = None,
    simulated_action_count: int | None = None,
    simulated_best_action_id: str | None = None,
    simulated_best_improvement: float | None = None,
    simulated_best_risk: float | None = None,
    simulated_horizon: int | None = None,
    simulated_global_flags: "tuple[str, ...] | None" = None,
    calibration_error: float | None = None,
    calibration_confidence: float | None = None,
    calibration_trend_bias: float | None = None,
    calibration_risk_bias: float | None = None,
    dynamics_trend_multiplier: float | None = None,
    dynamics_risk_multiplier: float | None = None,
    dynamics_stability_modifier: float | None = None,
    dynamics_confidence_scale: float | None = None,
    policy_world_count: int | None = None,
    policy_variance: float | None = None,
    policy_worst_case: float | None = None,
    policy_robust_score: float | None = None,
    objective_arb_mode: str | None = None,
    objective_arb_reward_weight: float | None = None,
    objective_arb_risk_weight: float | None = None,
    objective_arb_stability_weight: float | None = None,
    objective_arb_shift_reason: str | None = None,
    strat_pattern_match_found: bool | None = None,
    strat_pattern_confidence: float | None = None,
    strat_pattern_bias_applied: bool | None = None,
    strat_pattern_id: str | None = None,
    meta_control_mode: str | None = None,
    meta_control_agreement: float | None = None,
    meta_control_instability: float | None = None,
    meta_control_enabled_layers: "tuple[str, ...] | None" = None,
    policy_oscillation_score: float | None = None,
    policy_consistency_score: float | None = None,
    policy_flags: dict | None = None,
    intent_source: str | None = None,
    intent_compiled_weights: dict | None = None,
    intent_applied_biases: dict | None = None,
    executable_action_id: str | None = None,
    executable_action_type: str | None = None,
    executable_action_name: str | None = None,
    executable_target: str | None = None,
    executable_domain: str | None = None,
    executable_warnings: "tuple[str, ...] | None" = None,
    execution_status: str | None = None,
    execution_handler: str | None = None,
    execution_resolution_path: str | None = None,
    execution_error: str | None = None,
    feedback_outcome_type: str | None = None,
    feedback_signal_strength: float | None = None,
    feedback_action_id: str | None = None,
    feedback_ingested: bool | None = None,
    feedback_warnings: "tuple[str, ...] | None" = None,
    credit_score: float | None = None,
    credit_attribution: float | None = None,
    effective_credit: float | None = None,
    learning_signal_applied: bool | None = None,
    learning_signal_strength: float | None = None,
    strategy_prototype_id: str | None = None,
    strategy_match_score: float | None = None,
    strategy_bias_applied: bool | None = None,
    system_graph_id: str | None = None,
    system_node_execution_order: "tuple[str, ...] | None" = None,
    system_node_statuses: dict | None = None,
    system_status: str | None = None,
    environment: str | None = None,
    adapter_used: str | None = None,
    adapter_result_status: bool | None = None,
    adapter_latency: int | None = None,
    system_template_used: str | None = None,
    system_match_score: float | None = None,
    system_source: str | None = None,
) -> DecisionTrace:
    """Assemble a DecisionTrace from post-turn data.

    Reads strategy state from the global strategy memory singleton.
    All inputs are optional — missing data produces safe defaults.
    """
    evaluation = evaluation or {}

    # ── Strategy snapshot ────────────────────────────────────────────────
    # When conditioning_bias contains strategy_bias entries, pass them
    # through to rank_strategies() so ranking reflects world-state context.
    strategies_considered: tuple[str, ...] = ()
    strategy_scores: dict[str, float] = {}
    selected_strategy = ""
    _strat_bias: dict[str, float] | None = None
    if conditioning_bias and isinstance(conditioning_bias, dict):
        _sb = conditioning_bias.get("strategy_bias")
        if _sb and isinstance(_sb, dict):
            _strat_bias = _sb
    _strat_transfer: dict[str, float] | None = None
    if strategy_transfer_scores and isinstance(strategy_transfer_scores, dict):
        _strat_transfer = strategy_transfer_scores
    try:
        from umh.strategy.memory import get_strategy_memory

        mem = get_strategy_memory()
        current_turn = mem.global_turn
        ranked = mem.rank_strategies(
            conditioning_bias=_strat_bias,
            transfer_scores=_strat_transfer,
        )
        if ranked:
            strategies_considered = tuple(name for name, _ in ranked)
            strategy_scores = {
                name: round(
                    stats.effective_score(current_turn)
                    + (_strat_bias or {}).get(name, 0.0)
                    + (_strat_transfer or {}).get(name, 0.0),
                    4,
                )
                for name, stats in ranked
            }
            selected_strategy = ranked[0][0]

            if _strat_bias or _strat_transfer:
                _base, _cond = mem.get_conditioned_scores(
                    conditioning_bias=_strat_bias,
                    transfer_scores=_strat_transfer,
                )
                strategy_base_scores = strategy_base_scores or _base
                strategy_conditioned_scores = strategy_conditioned_scores or _cond
    except Exception:
        pass

    # ── Evaluation fields ────────────────────────────────────────────────
    quality_score = evaluation.get("quality_score", 0.0)
    confidence = evaluation.get("confidence", 0.0)

    # ── Signal attribution ───────────────────────────────────────────────
    attributed_dict: dict = {}
    horizon_dict: dict = {}
    if signals is not None:
        try:
            attributed_dict = signals.to_dict()
            horizon_dict = attributed_dict.pop("horizon", {})
        except Exception:
            pass

    # ── Result metadata ──────────────────────────────────────────────────
    model_used = getattr(result, "model_used", "unknown") if result else "unknown"
    latency_ms = getattr(result, "latency_ms", 0) if result else 0
    tokens_used = getattr(result, "tokens_used", None) if result else None
    was_enhanced = getattr(result, "was_enhanced", False) if result else False

    trace = DecisionTrace(
        turn_id=turn_id,
        strategies_considered=strategies_considered,
        strategy_scores=strategy_scores,
        selected_strategy=selected_strategy,
        quality_score=quality_score,
        confidence=confidence,
        signals=evaluation,
        attributed_signals=attributed_dict,
        horizon=horizon_dict,
        directives_applied=tuple(directives or ()),
        model_used=model_used,
        latency_ms=latency_ms,
        tokens_used=tokens_used,
        was_enhanced=was_enhanced,
        control_decision=control_decision,
        thresholds_used=thresholds_used,
        strategy_selection=strategy_selection,
        synthesized_strategy=synthesized_strategy,
        synthesis_reason=synthesis_reason,
        goal_mode=goal_mode,
        convergence_status=convergence_status,
        convergence_reason=convergence_reason,
        convergence_action=convergence_action,
        unified_influence=unified_influence,
        goal_score=goal_score,
        goal_delta=goal_delta,
        goal_confidence=goal_confidence,
        exploration_enabled=exploration_enabled,
        synthesis_enabled=synthesis_enabled,
        goal_gating_reason=goal_gating_reason,
        active_goal_id=active_goal_id,
        goal_pool_snapshot=goal_pool_snapshot,
        blended_goals=blended_goals,
        blended_primary_goal_id=blended_primary_goal_id,
        blended_entropy=blended_entropy,
        execution_budget=execution_budget,
        candidate_distribution=candidate_distribution,
        memory_persisted=memory_persisted,
        memory_version=memory_version,
        persistence_loaded=persistence_loaded,
        persistence_saved=persistence_saved,
        persistence_version=persistence_version,
        persisted_components=persisted_components,
        persistence_error=persistence_error,
        outcome_attached=outcome_attached,
        outcome_score=outcome_score,
        attribution_weights=attribution_weights,
        attribution_reason=attribution_reason,
        exploration_rate=exploration_rate,
        exploration_reason=exploration_reason,
        det_exploration_active=det_exploration_active,
        det_exploration_adjustments=det_exploration_adjustments,
        generated_goals=generated_goals,
        goal_mutations=goal_mutations,
        meta_goal_reason=meta_goal_reason,
        goal_validation_results=goal_validation_results,
        rejected_goals=rejected_goals,
        validation_reason=validation_reason,
        goal_alignment_scores=goal_alignment_scores,
        alignment_penalties=alignment_penalties,
        alignment_decisions=alignment_decisions,
        counterfactual_expected_utility=counterfactual_expected_utility,
        counterfactual_confidence=counterfactual_confidence,
        counterfactual_reasoning=counterfactual_reasoning,
        counterfactual_uncertainty=counterfactual_uncertainty,
        counterfactual_exploration_boost=counterfactual_exploration_boost,
        counterfactual_horizon_value=counterfactual_horizon_value,
        counterfactual_horizon_reason=counterfactual_horizon_reason,
        persistence_streaks=persistence_streaks,
        commitment_bonuses=commitment_bonuses,
        switch_penalty_applied=switch_penalty_applied,
        strategy_mutations=strategy_mutations,
        strategy_origins=strategy_origins,
        mutation_reason=mutation_reason,
        active_plan_id=active_plan_id,
        active_plan_step=active_plan_step,
        plan_confidence=plan_confidence,
        plan_count=plan_count,
        plan_generation_reason=plan_generation_reason,
        world_state_id=world_state_id,
        world_state_cluster=world_state_cluster,
        world_state_similarity=world_state_similarity,
        conditioning_bias=conditioning_bias,
        strategy_base_scores=strategy_base_scores,
        strategy_conditioned_scores=strategy_conditioned_scores,
        plan_step_goal_id=plan_step_goal_id,
        plan_step_attributed_score=plan_step_attributed_score,
        plan_step_attribution_source=plan_step_attribution_source,
        plan_step_status=plan_step_status,
        plan_step_retry_count=plan_step_retry_count,
        plan_step_failure_streak=plan_step_failure_streak,
        state_transfer_weight=state_transfer_weight,
        strategy_transfer_scores=strategy_transfer_scores,
        plan_transfer_score=plan_transfer_score,
        state_similarity_used=state_similarity_used,
        replan_adjustment=replan_adjustment,
        plan_mutation_applied=plan_mutation_applied,
        plan_mutation_type=plan_mutation_type,
        mutated_plan_id=mutated_plan_id,
        mutated_from_plan_id=mutated_from_plan_id,
        plan_recombination_applied=plan_recombination_applied,
        recombined_plan_id=recombined_plan_id,
        recombined_from_plan_ids=recombined_from_plan_ids,
        plan_evolution_reason=plan_evolution_reason,
        plan_origin_snapshot=plan_origin_snapshot,
        world_state_cluster_quality=world_state_cluster_quality,
        learned_state_bias=learned_state_bias,
        combined_state_bias=combined_state_bias,
        cluster_quality_ema=cluster_quality_ema,
        cluster_observation_count=cluster_observation_count,
        world_state_reinforcement_applied=world_state_reinforcement_applied,
        influence_components=influence_components,
        influence_weights=influence_weights,
        final_influence_score=final_influence_score,
        influence_breakdown=influence_breakdown,
        influence_applied=influence_applied,
        influence_adjustment=influence_adjustment,
        influence_pre_score=influence_pre_score,
        influence_post_score=influence_post_score,
        meta_weights=meta_weights,
        meta_weight_adjustments=meta_weight_adjustments,
        meta_weight_signal_performance=meta_weight_signal_performance,
        active_policy=active_policy,
        policy_reason=policy_reason,
        policy_adjustments=policy_adjustments,
        active_directives=active_directives,
        directive_scores=directive_scores,
        directive_selection_reason=directive_selection_reason,
        directive_evolution_events=directive_evolution_events,
        memory_entries_written=memory_entries_written,
        memory_queries_used=memory_queries_used,
        memory_aggregation_summary=memory_aggregation_summary,
        fabric_analytics_summary=fabric_analytics_summary,
        analytics_signal=analytics_signal,
        analytics_applied=analytics_applied,
        objective_snapshot=objective_snapshot,
        objective_value=objective_value,
        objective_trend=objective_trend,
        optimization_signal=optimization_signal,
        objective_history_length=objective_history_length,
        objective_persisted=objective_persisted,
        objective_decision_signal=objective_decision_signal,
        trap_signal_active=trap_signal_active,
        trap_adjustment=trap_adjustment,
        restart_state_loaded=restart_state_loaded,
        meta_signal_strength=meta_signal_strength,
        stability_guard_active=stability_guard_active,
        context_signal=context_signal,
        context_type=context_type,
        meta_generalization_matched=meta_generalization_matched,
        meta_generalization_prototype_id=meta_generalization_prototype_id,
        meta_generalization_similarity=meta_generalization_similarity,
        meta_generalization_priors=meta_generalization_priors,
        meta_generalization_signature=meta_generalization_signature,
        meta_generalization_prototype_usage=meta_generalization_prototype_usage,
        meta_generalization_prototype_avg_reward=meta_generalization_prototype_avg_reward,
        meta_generalization_suppressed=meta_generalization_suppressed,
        causal_signal=causal_signal,
        causal_confidence=causal_confidence,
        causal_applied=causal_applied,
        causal_context_match=causal_context_match,
        causal_credit=causal_credit,
        immediate_credit=immediate_credit,
        delayed_credit=delayed_credit,
        structural_credit=structural_credit,
        credit_reason=credit_reason,
        credited_entities=credited_entities,
        credit_signal=credit_signal,
        credit_confidence=credit_confidence,
        credit_applied=credit_applied,
        credit_horizon=credit_horizon,
        foresight_signal=foresight_signal,
        foresight_confidence=foresight_confidence,
        foresight_applied=foresight_applied,
        foresight_depth=foresight_depth,
        orchestration_consensus=orchestration_consensus,
        orchestration_active_count=orchestration_active_count,
        orchestration_suppressed_count=orchestration_suppressed_count,
        orchestration_dominant_source=orchestration_dominant_source,
        sensitivity_factor=sensitivity_factor,
        sensitivity_reason=sensitivity_reason,
        sensitivity_applied=sensitivity_applied,
        planner_active=planner_active,
        planner_scores=planner_scores,
        planner_choice=planner_choice,
        planner_confidence=planner_confidence,
        planner_reason=planner_reason,
        planner_horizon=planner_horizon,
        planner_uncertainty=planner_uncertainty,
        planner_consistency=planner_consistency,
        planner_adjusted_confidence=planner_adjusted_confidence,
        world_snapshot_version=world_snapshot_version,
        world_observation_count=world_observation_count,
        world_entity_count=world_entity_count,
        world_relation_count=world_relation_count,
        ingested_signal_count=ingested_signal_count,
        ingested_signal_sources=ingested_signal_sources,
        world_derived_count=world_derived_count,
        world_global_flags=world_global_flags,
        world_riskiest_entity=world_riskiest_entity,
        world_riskiest_entity_health=world_riskiest_entity_health,
        world_volatile_entity_count=world_volatile_entity_count,
        world_bad_entity_count=world_bad_entity_count,
        simulation_ran=simulation_ran,
        simulated_action_count=simulated_action_count,
        simulated_best_action_id=simulated_best_action_id,
        simulated_best_improvement=simulated_best_improvement,
        simulated_best_risk=simulated_best_risk,
        simulated_horizon=simulated_horizon,
        simulated_global_flags=simulated_global_flags,
        calibration_error=calibration_error,
        calibration_confidence=calibration_confidence,
        calibration_trend_bias=calibration_trend_bias,
        calibration_risk_bias=calibration_risk_bias,
        dynamics_trend_multiplier=dynamics_trend_multiplier,
        dynamics_risk_multiplier=dynamics_risk_multiplier,
        dynamics_stability_modifier=dynamics_stability_modifier,
        dynamics_confidence_scale=dynamics_confidence_scale,
        policy_world_count=policy_world_count,
        policy_variance=policy_variance,
        policy_worst_case=policy_worst_case,
        policy_robust_score=policy_robust_score,
        objective_arb_mode=objective_arb_mode,
        objective_arb_reward_weight=objective_arb_reward_weight,
        objective_arb_risk_weight=objective_arb_risk_weight,
        objective_arb_stability_weight=objective_arb_stability_weight,
        objective_arb_shift_reason=objective_arb_shift_reason,
        strat_pattern_match_found=strat_pattern_match_found,
        strat_pattern_confidence=strat_pattern_confidence,
        strat_pattern_bias_applied=strat_pattern_bias_applied,
        strat_pattern_id=strat_pattern_id,
        meta_control_mode=meta_control_mode,
        meta_control_agreement=meta_control_agreement,
        meta_control_instability=meta_control_instability,
        meta_control_enabled_layers=meta_control_enabled_layers,
        policy_oscillation_score=policy_oscillation_score,
        policy_consistency_score=policy_consistency_score,
        policy_flags=policy_flags,
        intent_source=intent_source,
        intent_compiled_weights=intent_compiled_weights,
        intent_applied_biases=intent_applied_biases,
        executable_action_id=executable_action_id,
        executable_action_type=executable_action_type,
        executable_action_name=executable_action_name,
        executable_target=executable_target,
        executable_domain=executable_domain,
        executable_warnings=executable_warnings,
        execution_status=execution_status,
        execution_handler=execution_handler,
        execution_resolution_path=execution_resolution_path,
        execution_error=execution_error,
        feedback_outcome_type=feedback_outcome_type,
        feedback_signal_strength=feedback_signal_strength,
        feedback_action_id=feedback_action_id,
        feedback_ingested=feedback_ingested,
        feedback_warnings=feedback_warnings,
        credit_score=credit_score,
        credit_attribution=credit_attribution,
        effective_credit=effective_credit,
        learning_signal_applied=learning_signal_applied,
        learning_signal_strength=learning_signal_strength,
        strategy_prototype_id=strategy_prototype_id,
        strategy_match_score=strategy_match_score,
        strategy_bias_applied=strategy_bias_applied,
        system_graph_id=system_graph_id,
        system_node_execution_order=system_node_execution_order,
        system_node_statuses=system_node_statuses,
        system_status=system_status,
        environment=environment,
        adapter_used=adapter_used,
        adapter_result_status=adapter_result_status,
        adapter_latency=adapter_latency,
        system_template_used=system_template_used,
        system_match_score=system_match_score,
        system_source=system_source,
    )

    if DEBUG_TRACE:
        debug_print(trace)

    return trace
