"""Confined independent verifier (C-4) — one canonical verifier-isolation authority.

Every verification check that executes code from the worker-controlled integration
tree (pytest, ``conftest.py``, worker-authored test modules, scripts, imports,
binaries) MUST run through this seam. No verifier may execute worker-authored code
directly in the runner host environment.

The defect this closes: ``field_control_plane._independent_checks_for`` ran
``python3 -m pytest`` with ``cwd=<lease worktree>`` via ``gated_subprocess_run`` —
no bwrap, no env scrub, the full host env including ``CLAUDE_CODE_OAUTH_TOKEN``. A
worktree ``conftest.py`` is arbitrary Python that pytest imports and executes, so
the verifier ran untrusted worker code unconfined moments after the worker runner
itself refused to start without bwrap.

The seam (``run_confined_verifier_checks``):

- mints a DISTINCT verifier lease + identity/role for the run (never the worker
  lease/identity/home/credential);
- runs worker-authored code ONLY inside bubblewrap — bwrap absent / launch failure
  / preflight unproven all FAIL CLOSED, never an unconfined fallback;
- exposes the integration source READ-ONLY, a credential-free private HOME, and a
  private TMPDIR — /opt/OS, /root/.claude, worker homes, the dispatch secret file,
  and candidate state are simply not in the namespace;
- unshares the network for worker-authored code;
- strips every credential (OAuth token, dispatch secret, API keys, mesh/Fly/GitHub/
  1Password, worker CLAUDE_CONFIG_DIR) from the subprocess env;
- proves ZERO source mutation with a PARENT-SIDE pre/post integrity check
  (rev-parse + status --porcelain + file hashes) — never trusts the subprocess to
  self-report it changed nothing;
- persists hashed, name-only evidence bound to the AttemptProof lineage;
- destroys the verifier lease/home/tmp on EVERY terminal path (pass, failure,
  timeout, cancellation, exception, teardown); cleanup failure is a BLOCKING
  security failure, never a warning.

``verify_attempt`` (verification.py) CONSUMES the resulting
``VerificationCheck`` list; it never invokes worker-tree callbacks on the host.
"""

from __future__ import annotations

import hashlib
import logging
import os
import time
import uuid
from dataclasses import dataclass, field
from typing import Any

from substrate.execution.attempts.host_isolation import (
    IsolationUnavailable,
    VerifierIsolationProfile,
    build_isolated_verifier_command,
    isolation_primitive,
    preflight_isolation,
    scrub_verifier_env,
)
from substrate.execution.attempts.worker_credential_boundary import (
    AttemptHome,
    CredentialBoundaryError,
    close_attempt_credential_home,
    open_verifier_home,
)

logger = logging.getLogger(__name__)


class VerifierIsolationError(RuntimeError):
    """Verification could not be run confined. Always fail closed."""


@dataclass
class VerifierLease:
    """The distinct verifier lease for one verification run.

    Never the implementation worker lease. Carries its own identity/role, the
    exact commit being verified, and the private HOME/XDG/TMP the confined
    subprocess uses. ``home`` holds NO credential.
    """

    verifier_lease_id: str
    attempt_id: str
    task_id: str
    verifier_identity: str
    verifier_role_id: str
    source_commit: str
    home: AttemptHome
    source_ro_path: str
    created_at: float = field(default_factory=time.time)
    closed: bool = False

    def env_overrides(self) -> dict[str, str]:
        """HOME/XDG/TMPDIR pointing ONLY at verifier-private directories."""
        return self.home.env_overrides()

    def to_dict(self) -> dict[str, Any]:
        return {
            "verifier_lease_id": self.verifier_lease_id,
            "attempt_id": self.attempt_id,
            "task_id": self.task_id,
            "verifier_identity": self.verifier_identity,
            "verifier_role_id": self.verifier_role_id,
            "source_commit": self.source_commit,
            "home_path": self.home.home_path,
            "tmp_path": self.home.tmp_path,
            "source_ro_path": self.source_ro_path,
            "closed": self.closed,
        }


VERIFIER_EVIDENCE_TYPE = "verifier_confined_run"


@dataclass
class VerifierEvidence:
    """Parent-side, hashed, name-only evidence for one confined verification.

    Bound to the AttemptProof lineage AND persisted inside the exact AttemptProof
    (C-4a). Contains NO secret values — env is names only, the bwrap argv is
    redaction-safe (no secret ever transits it), and file hashes prove integrity
    without exposing content.

    ``base_commit`` is the authorized diff base (lease snapshot_ref);
    ``verified_commit`` is the ACTUAL integration/worktree HEAD the verifier
    tested — they are distinct fields and must never be conflated.

    ``process_identity`` is generated by the TRUSTED PARENT (a wrapper that writes
    PID + start time + executable + invocation nonce before exec), never by
    worker-authored code, never ``0``/``None``/``unknown``.
    """

    # lineage (bound into the digest + the AttemptProof)
    verifier_lease_id: str
    attempt_id: str
    task_id: str
    assignment_id: str
    verifier_identity: str
    verifier_role_id: str
    worker_identity: str
    package_hash: str
    # commit binding — base and verified are DISTINCT
    base_commit: str
    verified_commit: str
    # confinement claim
    bwrap_argv: list[str]
    bwrap_argv_digest: str
    env_var_names: list[str]
    mount_policy: dict[str, Any]
    isolation_probe: dict[str, Any]
    source_hashes_before: dict[str, str]
    source_hashes_after: dict[str, str]
    zero_diff: bool
    tests_ok: bool
    tests_detail: str
    started_at: float
    ended_at: float
    process_identity: dict[str, Any]
    verifier_pid: int
    evidence_sha256: str = ""

    def _canonical_payload(self) -> dict[str, Any]:
        """The complete canonical payload hashed by ``finalize`` — every claimed
        field (lineage, both commits, timestamps, process identity, isolation
        results). ``evidence_sha256`` is DELIBERATELY excluded (never hashed into
        itself)."""
        return {
            "verifier_lease_id": self.verifier_lease_id,
            "attempt_id": self.attempt_id,
            "task_id": self.task_id,
            "assignment_id": self.assignment_id,
            "verifier_identity": self.verifier_identity,
            "verifier_role_id": self.verifier_role_id,
            "worker_identity": self.worker_identity,
            "package_hash": self.package_hash,
            "base_commit": self.base_commit,
            "verified_commit": self.verified_commit,
            "bwrap_argv": list(self.bwrap_argv),
            "bwrap_argv_digest": self.bwrap_argv_digest,
            "env_var_names": sorted(self.env_var_names),
            "mount_policy": self.mount_policy,
            "isolation_probe": self.isolation_probe,
            "source_hashes_before": self.source_hashes_before,
            "source_hashes_after": self.source_hashes_after,
            "zero_diff": self.zero_diff,
            "tests_ok": self.tests_ok,
            "tests_detail": self.tests_detail,
            "started_at": self.started_at,
            "ended_at": self.ended_at,
            "process_identity": self.process_identity,
            "verifier_pid": self.verifier_pid,
        }

    def finalize(self) -> "VerifierEvidence":
        self.evidence_sha256 = _hash_json(self._canonical_payload())
        return self

    def recompute_digest(self) -> str:
        """Recompute the digest from the current fields (for reread validation)."""
        return _hash_json(self._canonical_payload())

    def to_dict(self) -> dict[str, Any]:
        return dict(self.__dict__)

    @classmethod
    def from_dict(cls, d: dict[str, Any]) -> "VerifierEvidence":
        fields = {
            k: d.get(k)
            for k in (
                "verifier_lease_id",
                "attempt_id",
                "task_id",
                "assignment_id",
                "verifier_identity",
                "verifier_role_id",
                "worker_identity",
                "package_hash",
                "base_commit",
                "verified_commit",
                "bwrap_argv",
                "bwrap_argv_digest",
                "env_var_names",
                "mount_policy",
                "isolation_probe",
                "source_hashes_before",
                "source_hashes_after",
                "zero_diff",
                "tests_ok",
                "tests_detail",
                "started_at",
                "ended_at",
                "process_identity",
                "verifier_pid",
                "evidence_sha256",
            )
        }
        return cls(**fields)


def _hash_json(obj: Any) -> str:
    import json

    return hashlib.sha256(json.dumps(obj, sort_keys=True, default=str).encode()).hexdigest()


def _hash_file(path: str) -> str:
    h = hashlib.sha256()
    try:
        with open(path, "rb") as fh:
            for chunk in iter(lambda: fh.read(65536), b""):
                h.update(chunk)
    except OSError:
        return "unreadable"
    return h.hexdigest()


def _source_tree_hashes(source: str) -> dict[str, str]:
    """SHA-256 of every tracked+untracked source file (parent-side integrity).

    Order-independent map ``relpath -> sha256``. Excludes ``.git`` internals (the
    verifier never touches them and their churn is not a source mutation).
    """
    hashes: dict[str, str] = {}
    for dirpath, dirnames, filenames in os.walk(source):
        if ".git" in dirnames:
            dirnames.remove(".git")
        for name in filenames:
            full = os.path.join(dirpath, name)
            rel = os.path.relpath(full, source)
            hashes[rel] = _hash_file(full)
    return hashes


def _git(source: str, args: list[str]) -> tuple[int, str]:
    """Run a git command in ``source`` via the gated subprocess. (int rc, stdout)."""
    from substrate.execution.cpu_gate import gated_subprocess_run

    result = gated_subprocess_run(
        ["git", *args],
        caller="wave2_verifier_source_integrity",
        timeout=60,
        cwd=source,
    )
    if result is None:
        return 1, ""
    return result.returncode, (result.stdout or "")


def _parent_side_head(source: str) -> tuple[bool, str]:
    """Full-SHA HEAD read PARENT-SIDE. (ok, sha). Fails closed on empty/short."""
    rc, out = _git(source, ["rev-parse", "HEAD"])
    sha = out.strip()
    if rc != 0 or len(sha) < 40:  # require a full 40-hex SHA, never a short/empty one
        return False, sha
    return True, sha


def _build_pid_wrapper(inner_cmd: list[str], *, pid_record_path: str, nonce: str) -> list[str]:
    """Wrap ``inner_cmd`` so the child writes a TRUSTED process-identity record
    BEFORE exec (approach B).

    The parent generates ``nonce`` and the ``pid_record_path``; the wrapper writes
    ``pid|start_epoch|argv0|nonce`` to that path inside the verifier-private tmp,
    then exec's the real command. Worker-authored code never runs before this, and
    the nonce is parent-generated, so the identity cannot be forged by the payload.

    ``pid_record_path`` is inside the verifier's private TMPDIR (bound rw), so the
    parent can read it back after the run. Uses ``exec`` so the recorded PID IS the
    test process's PID.
    """
    quoted = " ".join(_sh_quote(a) for a in inner_cmd)
    script = (
        f'printf "%s|%s|%s|%s\\n" "$$" "$(date +%s)" "{_sh_quote(inner_cmd[0])}" '
        f'"{nonce}" > {_sh_quote(pid_record_path)}; exec {quoted}'
    )
    return ["/bin/sh", "-c", script]


def _sh_quote(s: str) -> str:
    import shlex

    return shlex.quote(str(s))


def _read_pid_record(path: str, *, expected_nonce: str) -> dict[str, Any]:
    """Read + validate the trusted process-identity record. Fails closed.

    Returns a structured identity ``{pid, start_epoch, argv0, nonce, valid}``.
    ``valid`` is True only when the record parses AND the nonce matches the
    parent-generated one (so a payload cannot substitute a forged record)."""
    try:
        with open(path, encoding="utf-8") as fh:
            raw = fh.read().strip()
    except OSError:
        return {"pid": 0, "start_epoch": 0, "argv0": "", "nonce": "", "valid": False}
    parts = raw.split("|")
    if len(parts) != 4:
        return {"pid": 0, "start_epoch": 0, "argv0": "", "nonce": "", "valid": False}
    pid_s, start_s, argv0, nonce = parts
    try:
        pid = int(pid_s)
        start_epoch = int(start_s)
    except ValueError:
        return {"pid": 0, "start_epoch": 0, "argv0": "", "nonce": "", "valid": False}
    valid = bool(pid) and nonce == expected_nonce
    return {
        "pid": pid,
        "start_epoch": start_epoch,
        "argv0": argv0,
        "nonce": nonce,
        "valid": valid,
    }


# ── lifecycle ────────────────────────────────────────────────────────────────
def open_verifier_lease(
    *,
    attempt_id: str,
    task_id: str,
    run_root: str,
    source_ro_path: str,
    verifier_role_id: str,
    worker_identity: str,
    source_commit: str = "",
) -> VerifierLease:
    """Create the distinct verifier lease + credential-free private home.

    Fails closed if the verifier identity would collide with the worker (an agent
    can never verify its own work), or if the private home cannot be created.
    """
    if not attempt_id:
        raise VerifierIsolationError("attempt_id is required for a verifier lease")
    if not source_ro_path or not os.path.isdir(source_ro_path):
        raise VerifierIsolationError(
            f"verifier source path {source_ro_path!r} is not a directory — refusing"
        )
    verifier_identity = f"verifier:{verifier_role_id}:{attempt_id}"
    if worker_identity and verifier_identity == worker_identity:
        raise VerifierIsolationError(
            f"verifier identity {verifier_identity!r} collides with worker "
            f"{worker_identity!r} — separation of duty violated"
        )
    home = open_verifier_home(attempt_id=attempt_id, run_root=run_root)
    return VerifierLease(
        verifier_lease_id=f"vlease-{uuid.uuid4().hex[:12]}",
        attempt_id=attempt_id,
        task_id=task_id,
        verifier_identity=verifier_identity,
        verifier_role_id=verifier_role_id,
        source_commit=source_commit,
        home=home,
        source_ro_path=os.path.realpath(source_ro_path),
    )


def close_verifier_lease(lease: VerifierLease | None) -> None:
    """Destroy the verifier private home/tmp. Cleanup failure is a SECURITY failure.

    Reuses ``close_attempt_credential_home`` (idempotent, raises on residue). Safe
    on every terminal path.
    """
    if lease is None or lease.closed:
        return
    close_attempt_credential_home(lease.home)  # raises CredentialBoundaryError on residue
    lease.closed = True


# ── the one confined verification entry point ─────────────────────────────────
def run_confined_verifier_checks(
    *,
    attempt: Any,
    run_root: str,
    source_path: str,
    verifier_role_id: str,
    worker_identity: str,
    base_commit: str = "",
    expected_result_commit: str = "",
    assignment_id: str = "",
    package_hash: str = "",
    test_argv: list[str] | None = None,
    timeout_s: int = 300,
) -> tuple[list[Any], VerifierEvidence]:
    """Run the verifier's worker-code checks CONFINED, returning (checks, evidence).

    ``checks`` are ``VerificationCheck`` objects ``verify_attempt`` consumes. The
    integration ``source_path`` is mounted READ-ONLY inside bwrap; pytest (which
    imports the worker's ``conftest.py``) runs with the network unshared, a
    credential-free HOME, and a scrubbed env. Parent-side pre/post hashes + git
    status prove zero source mutation. Every terminal path destroys the lease.

    Commit binding (C-4a): ``base_commit`` is the authorized diff base
    (lease.snapshot_ref). ``verified_commit`` is the ACTUAL worktree HEAD, read
    PARENT-SIDE before the run — it is NEVER ``base_commit``. When
    ``expected_result_commit`` is supplied and differs from the read HEAD, or HEAD
    moves during verification, verification FAILS closed.

    FAIL CLOSED: bwrap absent, launch failure, preflight unproven, a
    verifier-produced source diff, a commit-binding mismatch, or an unverifiable
    process identity each yields a FAILED check (never an unconfined run and never
    a self-reported clean).
    """
    from substrate.execution.attempts.verification import VerificationCheck

    started = time.time()
    lease: VerifierLease | None = None
    checks: list[Any] = []
    attempt_id = getattr(attempt, "attempt_id", "") or ""
    task_id = getattr(attempt, "task_id", "") or ""

    # 1. bwrap must be present. No fallback to a coarser primitive or host subprocess.
    prim = isolation_primitive()
    if prim != "bwrap":
        checks.append(
            VerificationCheck(
                check_id="verifier_isolation",
                kind="policy",
                ok=False,
                detail=f"bwrap unavailable (primitive={prim!r}) — refusing to verify unconfined",
            )
        )
        return checks, _fail_evidence(base_commit, started, f"no bwrap (prim={prim})")

    # 2. preflight: prove the sandbox genuinely hides a forbidden path.
    probe_ok, probe_detail = preflight_isolation("/opt/OS")
    if not probe_ok:
        checks.append(
            VerificationCheck(
                check_id="verifier_isolation",
                kind="policy",
                ok=False,
                detail=f"isolation preflight not proven: {probe_detail}",
            )
        )
        return checks, _fail_evidence(base_commit, started, f"preflight failed: {probe_detail}")

    try:
        # verified_commit is read PARENT-SIDE from the worktree HEAD — never the
        # base. A missing/short SHA fails closed.
        head_ok, verified_commit = _parent_side_head(source_path)
        if not head_ok:
            checks.append(
                VerificationCheck(
                    check_id="verifier_commit_binding",
                    kind="policy",
                    ok=False,
                    detail=f"could not read a full worktree HEAD ({verified_commit!r})",
                )
            )
            return checks, _fail_evidence(base_commit, started, "no worktree HEAD")
        # An expected worker/integration result commit must match the tested HEAD.
        if expected_result_commit and expected_result_commit != verified_commit:
            checks.append(
                VerificationCheck(
                    check_id="verifier_commit_binding",
                    kind="policy",
                    ok=False,
                    detail=(
                        f"HEAD {verified_commit} != expected result commit {expected_result_commit}"
                    ),
                )
            )
            return checks, _fail_evidence(base_commit, started, "expected-commit mismatch")

        lease = open_verifier_lease(
            attempt_id=attempt_id,
            task_id=task_id,
            run_root=run_root,
            source_ro_path=source_path,
            verifier_role_id=verifier_role_id,
            worker_identity=worker_identity,
            source_commit=verified_commit,
        )
        source = lease.source_ro_path

        # 3. PARENT-SIDE integrity snapshot BEFORE running worker code.
        before_hashes = _source_tree_hashes(source)

        # 4. build the confined command wrapped so the child writes a TRUSTED
        #    process-identity record (parent-generated nonce) before exec.
        inner = test_argv or ["python3", "-m", "pytest", "-q", "-p", "no:cacheprovider"]
        nonce = uuid.uuid4().hex
        pid_record = os.path.join(lease.home.tmp_path, f"verifier_proc_{nonce}.id")
        wrapped_inner = _build_pid_wrapper(inner, pid_record_path=pid_record, nonce=nonce)
        profile = VerifierIsolationProfile(
            source_ro_path=source,
            verifier_home=lease.home.home_path,
            tmp_path=lease.home.tmp_path,
            allow_network=False,  # worker-authored code gets NO network
            env_overrides=lease.env_overrides(),
        )
        argv = build_isolated_verifier_command(wrapped_inner, profile)
        scrubbed_env = scrub_verifier_env(dict(os.environ))
        scrubbed_env.update(lease.env_overrides())

        from substrate.execution.cpu_gate import gated_subprocess_run

        result = gated_subprocess_run(
            argv,
            caller="wave2_confined_verifier_tests",
            timeout=timeout_s,
            env=scrubbed_env,
        )

        # 5. PARENT-SIDE integrity check AFTER — never trust the subprocess.
        after_hashes = _source_tree_hashes(source)
        head_ok_after, head_after = _parent_side_head(source)
        rc_status, status_out = _git(source, ["status", "--porcelain"])
        dirty = bool(status_out.strip())
        hashes_changed = before_hashes != after_hashes
        head_moved = (not head_ok_after) or head_after != verified_commit
        zero_diff = not dirty and not hashes_changed and not head_moved

        # 6. TRUSTED process identity (parent wrapper). No pid → fail closed.
        proc_identity = _read_pid_record(pid_record, expected_nonce=nonce)
        proc_ok = bool(proc_identity.get("valid")) and int(proc_identity.get("pid") or 0) > 0
        verifier_pid = int(proc_identity.get("pid") or 0)

        if result is None:
            tests_ok = False
            tests_detail = "verifier test run skipped by CPU gate — cannot confirm"
        else:
            tests_ok = result.returncode == 0
            tests_detail = f"pytest rc={result.returncode} (confined, net-unshared)"

        checks.append(
            VerificationCheck(
                check_id="verifier_zero_diff",
                kind="policy",
                ok=zero_diff,
                detail=(
                    "source unchanged (hashes + HEAD + status all clean)"
                    if zero_diff
                    else f"SOURCE MUTATED: dirty={dirty} hashes_changed={hashes_changed} "
                    f"head_moved={head_moved}"
                ),
            )
        )
        checks.append(
            VerificationCheck(
                check_id="verifier_commit_binding",
                kind="policy",
                ok=head_ok_after and not head_moved,
                detail=f"verified_commit={verified_commit} base_commit={base_commit}",
            )
        )
        checks.append(
            VerificationCheck(
                check_id="verifier_process_identity",
                kind="policy",
                ok=proc_ok,
                detail=(
                    f"trusted pid={verifier_pid} nonce-matched"
                    if proc_ok
                    else "process identity unverifiable (no trusted pid record)"
                ),
            )
        )
        checks.append(
            VerificationCheck(
                check_id="independent_tests",
                kind="tests",
                # tests only count if the source is intact, the commit binding
                # holds, and the process identity is trusted.
                ok=tests_ok and zero_diff and (head_ok_after and not head_moved) and proc_ok,
                detail=tests_detail,
            )
        )

        evidence = VerifierEvidence(
            verifier_lease_id=lease.verifier_lease_id,
            attempt_id=attempt_id,
            task_id=task_id,
            assignment_id=assignment_id,
            verifier_identity=lease.verifier_identity,
            verifier_role_id=verifier_role_id,
            worker_identity=worker_identity,
            package_hash=package_hash,
            base_commit=base_commit,
            verified_commit=verified_commit,
            bwrap_argv=argv,
            bwrap_argv_digest=_hash_json(argv),
            env_var_names=sorted(scrubbed_env.keys()),
            mount_policy={
                "source_ro": source,
                "writable": [lease.home.home_path, lease.home.tmp_path],
                "network": "unshared",
                "opt_os_bound": False,
                "root_claude_bound": False,
            },
            isolation_probe={"ok": probe_ok, "detail": probe_detail},
            source_hashes_before=before_hashes,
            source_hashes_after=after_hashes,
            zero_diff=zero_diff,
            tests_ok=tests_ok,
            tests_detail=tests_detail,
            started_at=started,
            ended_at=time.time(),
            process_identity=proc_identity,
            verifier_pid=verifier_pid,
        ).finalize()
        return checks, evidence

    except (VerifierIsolationError, IsolationUnavailable) as exc:
        checks.append(
            VerificationCheck(
                check_id="verifier_isolation",
                kind="policy",
                ok=False,
                detail=f"confined verification unavailable: {exc}",
            )
        )
        return checks, _fail_evidence(base_commit, started, str(exc))
    finally:
        # Destroy the verifier lease on EVERY terminal path. A cleanup failure is a
        # BLOCKING security failure: surface it as a failed check AND re-raise so no
        # caller can treat a leaked verifier home as a pass.
        if lease is not None:
            try:
                close_verifier_lease(lease)
            except CredentialBoundaryError as exc:
                checks.append(
                    VerificationCheck(
                        check_id="verifier_cleanup",
                        kind="policy",
                        ok=False,
                        detail=f"SECURITY: verifier home not destroyed: {exc}",
                    )
                )
                raise VerifierIsolationError(
                    f"verifier cleanup failed (blocking security failure): {exc}"
                ) from exc


def _fail_evidence(base_commit: str, started: float, reason: str) -> VerifierEvidence:
    """Evidence for a verification that never ran confined (fail-closed record)."""
    return VerifierEvidence(
        verifier_lease_id="",
        attempt_id="",
        task_id="",
        assignment_id="",
        verifier_identity="",
        verifier_role_id="",
        worker_identity="",
        package_hash="",
        base_commit=base_commit,
        verified_commit="",  # a fail-closed record NEVER claims a verified commit
        bwrap_argv=[],
        bwrap_argv_digest="",
        env_var_names=[],
        mount_policy={"reason": reason},
        isolation_probe={"ok": False, "detail": reason},
        source_hashes_before={},
        source_hashes_after={},
        zero_diff=False,
        tests_ok=False,
        tests_detail=reason,
        started_at=started,
        ended_at=time.time(),
        process_identity={"pid": 0, "valid": False},
        verifier_pid=0,
    ).finalize()


# ── reread / binding validation (post-persistence, restart-safe) ─────────────
class VerifierEvidenceBindingError(RuntimeError):
    """The AttemptProof's verifier evidence does not bind to this attempt. Fail closed."""


def evidence_from_proof(proof: Any) -> VerifierEvidence:
    """Extract the EXACTLY-ONE verifier evidence record from a durable Proof.

    Fails closed on: no verifier evidence, multiple verifier evidence records, or a
    record whose stored digest does not recompute (tamper). Works on a Proof reread
    from disk — no in-memory field is consulted.
    """
    records = [
        e
        for e in getattr(proof, "evidence", []) or []
        if getattr(e, "evidence_type", "") == VERIFIER_EVIDENCE_TYPE
    ]
    if len(records) == 0:
        raise VerifierEvidenceBindingError("Proof contains no verifier evidence record")
    if len(records) > 1:
        raise VerifierEvidenceBindingError(
            f"Proof contains {len(records)} verifier evidence records (need exactly 1)"
        )
    ev = VerifierEvidence.from_dict(getattr(records[0], "data", {}) or {})
    stored = ev.evidence_sha256
    if not stored or stored != ev.recompute_digest():
        raise VerifierEvidenceBindingError(
            "verifier evidence digest does not recompute — evidence tampered"
        )
    return ev


def validate_evidence_binding(
    proof: Any,
    *,
    attempt_id: str,
    task_id: str,
    assignment_id: str = "",
    verifier_identity: str = "",
    verified_commit: str = "",
    package_hash: str = "",
) -> VerifierEvidence:
    """Reread + validate that a durable Proof's verifier evidence binds to exactly
    this attempt. Fail closed on any mismatch. Returns the validated evidence.

    This is the restart-safe check: given a Proof reread from disk it reconstructs
    the binding without any in-memory field. A Proof that claims the base commit
    instead of the tested HEAD, another attempt's evidence, or a tampered digest
    all fail here.
    """
    ev = evidence_from_proof(proof)  # exactly-one + digest recompute
    mismatches: list[str] = []
    if attempt_id and ev.attempt_id != attempt_id:
        mismatches.append(f"attempt_id {ev.attempt_id!r}!={attempt_id!r}")
    if task_id and ev.task_id != task_id:
        mismatches.append(f"task_id {ev.task_id!r}!={task_id!r}")
    if assignment_id and ev.assignment_id != assignment_id:
        mismatches.append(f"assignment_id {ev.assignment_id!r}!={assignment_id!r}")
    if verifier_identity and ev.verifier_identity != verifier_identity:
        mismatches.append(f"verifier_identity {ev.verifier_identity!r}!={verifier_identity!r}")
    if verified_commit and ev.verified_commit != verified_commit:
        mismatches.append(f"verified_commit {ev.verified_commit!r}!={verified_commit!r}")
    if package_hash and ev.package_hash != package_hash:
        mismatches.append(f"package_hash {ev.package_hash!r}!={package_hash!r}")
    # a successful verifier evidence must carry a real verified commit + trusted pid
    if not ev.verified_commit:
        mismatches.append("verified_commit is empty")
    if not (ev.process_identity or {}).get("valid"):
        mismatches.append("process identity not trusted")
    if mismatches:
        raise VerifierEvidenceBindingError("; ".join(mismatches))
    return ev


__all__ = [
    "VERIFIER_EVIDENCE_TYPE",
    "VerifierIsolationError",
    "VerifierEvidenceBindingError",
    "VerifierLease",
    "VerifierEvidence",
    "open_verifier_lease",
    "close_verifier_lease",
    "run_confined_verifier_checks",
    "evidence_from_proof",
    "validate_evidence_binding",
]
