"""UMH Canonical Protocol Contracts.

Type-level anchor for the Universal Meta Harness.
All inter-module communication uses these typed protocols.

Imports flow OUT of protocols/, never IN.
Dependencies: standard library + pydantic only.
"""

from .adapters import (
    AccessPath,
    Adapter,
    AdapterPackage,
    Connection,
    ExternalRequest,
    ExternalResponse,
    NormalizedResult,
    StateSnapshot,
    ValidationResult,
)
from .common import (
    AdapterCategory,
    AdapterPackageRef,
    AdapterRef,
    ApprovalStatus,
    AuthorityContext,
    AuthorityLevel,
    Benchmark,
    CapabilityRef,
    ConfirmationStatus,
    Constraint,
    CostModel,
    EnvironmentRef,
    EnvironmentType,
    EvidenceRef,
    EvidenceType,
    FailureMode,
    GovernancePolicyRef,
    ItemStatus,
    LatencyModel,
    MasteryCategory,
    MasteryRef,
    MasteryStatus,
    MaturityStatus,
    MemoryRef,
    MemoryType,
    PacketStatus,
    Permission,
    PrimitiveType,
    PromotionStatus,
    ProofRequirement,
    RelationshipRef,
    RelationshipType,
    RiskLevel,
    Severity,
    SignalModality,
    SignalType,
    Slot,
    Step,
    TemplateRef,
    TestRef,
    WorkerRef,
    WorkflowRef,
)
from .composition import (
    Capability,
    Dependency,
    ExecutableComposition,
    FeedbackLoopSpec,
    GovernanceSpec,
    ImmutablePrimitive,
    MasteryGap,
    MasteryRequirement,
    MemoryUpdateRule,
    ObservabilitySpec,
    QualityCriterion,
    RegistryItem,
    Template,
)
from .control_plane import ControlPlaneEvent
from .execution import (
    ActionContract,
    Environment,
    NetworkState,
    OutputSpec,
    ResourceModel,
    StateTransition,
    SuccessCriterion,
    WorkPacket,
)
from .governance import (
    ApprovalRequirement,
    EnvironmentLimit,
    EscalationRule,
    GovernancePolicy,
    RiskModel,
)
from .learning import InternalSignal
from .observability import (
    ExecutionResult,
    FeedbackEvent,
    GovernanceDecision,
    Outcome,
    ParityResult,
    ProofArtifact,
    TimestampSet,
    Trace,
    WorldStateSnapshot,
)
from .state import (
    Fact,
    MemoryRecord,
    Resource,
    Risk,
    TemporalState,
    UncertaintyModel,
    WorldEntity,
    WorldState,
)
from .understanding import (
    DomainLaw,
    DomainMap,
    EntityType,
    IntentCandidate,
    InterpretedSignal,
    Primitive,
    PrimitiveMapping,
    Relationship,
    Signal,
    SlotSpec,
)

__all__ = [
    # common enums
    "AdapterCategory",
    "ApprovalStatus",
    "AuthorityLevel",
    "ConfirmationStatus",
    "EnvironmentType",
    "EvidenceType",
    "ItemStatus",
    "MasteryCategory",
    "MasteryStatus",
    "MaturityStatus",
    "MemoryType",
    "PacketStatus",
    "PrimitiveType",
    "PromotionStatus",
    "RelationshipType",
    "RiskLevel",
    "Severity",
    "SignalModality",
    "SignalType",
    # common refs
    "AdapterPackageRef",
    "AdapterRef",
    "CapabilityRef",
    "EnvironmentRef",
    "EvidenceRef",
    "GovernancePolicyRef",
    "MasteryRef",
    "MemoryRef",
    "RelationshipRef",
    "TemplateRef",
    "TestRef",
    "WorkerRef",
    "WorkflowRef",
    # common sub-models
    "AuthorityContext",
    "Benchmark",
    "Constraint",
    "CostModel",
    "FailureMode",
    "LatencyModel",
    "Permission",
    "ProofRequirement",
    "Slot",
    "Step",
    # control_plane
    "ControlPlaneEvent",
    # understanding
    "DomainLaw",
    "DomainMap",
    "EntityType",
    "IntentCandidate",
    "InterpretedSignal",
    "Primitive",
    "PrimitiveMapping",
    "Relationship",
    "Signal",
    "SlotSpec",
    # state
    "Fact",
    "MemoryRecord",
    "Resource",
    "Risk",
    "TemporalState",
    "UncertaintyModel",
    "WorldEntity",
    "WorldState",
    # composition
    "Capability",
    "Dependency",
    "ExecutableComposition",
    "FeedbackLoopSpec",
    "GovernanceSpec",
    "ImmutablePrimitive",
    "MasteryGap",
    "MasteryRequirement",
    "MemoryUpdateRule",
    "ObservabilitySpec",
    "QualityCriterion",
    "RegistryItem",
    "Template",
    # governance
    "ApprovalRequirement",
    "EnvironmentLimit",
    "EscalationRule",
    "GovernancePolicy",
    "RiskModel",
    # execution
    "ActionContract",
    "Environment",
    "NetworkState",
    "OutputSpec",
    "ResourceModel",
    "StateTransition",
    "SuccessCriterion",
    "WorkPacket",
    # adapters
    "AccessPath",
    "Adapter",
    "AdapterPackage",
    "Connection",
    "ExternalRequest",
    "ExternalResponse",
    "NormalizedResult",
    "StateSnapshot",
    "ValidationResult",
    # observability
    "ExecutionResult",
    "FeedbackEvent",
    "GovernanceDecision",
    "Outcome",
    "ParityResult",
    "ProofArtifact",
    "TimestampSet",
    "Trace",
    "WorldStateSnapshot",
    # learning
    "InternalSignal",
]
