#!/usr/bin/env python3
"""R8d — Deterministic compatibility shim generator.

Generates eos_ai/ shim layer that provides backward-compatible imports
by forwarding to canonical runtime/ modules. All shims use sys.modules
replacement for guaranteed identity preservation.

Shim pattern (leaf modules):
    # Generated by r8d_generate_shims.py — do not edit
    import runtime.{target} as _mod
    import sys as _sys
    _sys.modules[__name__] = _mod

Shim pattern (__init__.py packages):
    # Generated by r8d_generate_shims.py — do not edit
    import runtime.{target} as _mod
    import sys as _sys
    _sys.modules[__name__] = _mod

Reports:
    - Shim manifest (all generated shims with routing)
    - Coverage report (canonical modules with/without shims)
    - Orphan report (shims with no canonical target)
    - Oversized report (shims exceeding expected line count)
    - Private-name handling report (modules with known private consumers)

Usage:
    python3 scripts/r8d_generate_shims.py
    python3 scripts/r8d_generate_shims.py --dry-run
"""
import json
import os
import sys
import time
from pathlib import Path

REPO_ROOT = "/opt/OS"
RUNTIME_DIR = os.path.join(REPO_ROOT, "runtime")
EOS_AI_DIR = os.path.join(REPO_ROOT, "eos_ai")
HEADER = "# Generated by r8d_generate_shims.py — do not edit\n"
MAX_SHIM_LINES = 4

PRIVATE_NAME_CONSUMERS = {
    "eos_ai.runtime.work_state": "runtime.work_state",
    "eos_ai.runtime.provider_state": "runtime.provider_state",
    "eos_ai.goal_selector": "runtime.goal_selector",
    "eos_ai.substrate.claude_session_bridge": "runtime.transport.claude_session_bridge",
    "eos_ai.substrate.llm_planner": "runtime.transport.llm_planner",
    "eos_ai.substrate.session_watcher": "runtime.transport.session_watcher",
    "eos_ai.substrate.stt_producer": "runtime.transport.stt_producer",
    "eos_ai.substrate.workflow_execution": "runtime.transport.workflow_execution",
    "eos_ai.transport.claude_session_bridge": "runtime.transport.claude_session_bridge",
    "eos_ai.transport.llm_planner": "runtime.transport.llm_planner",
    "eos_ai.transport.session_watcher": "runtime.transport.session_watcher",
    "eos_ai.transport.stt_producer": "runtime.transport.stt_producer",
    "eos_ai.transport.work_order_contracts": "runtime.transport.work_order_contracts",
    "eos_ai.transport.workflow_execution": "runtime.transport.workflow_execution",
}


def _shim_content(target_module: str) -> str:
    return (
        f"{HEADER}"
        f"import {target_module} as _mod\n"
        f"import sys as _sys\n"
        f"_sys.modules[__name__] = _mod\n"
    )


def _init_shim_content(target_module: str) -> str:
    return (
        f"{HEADER}"
        f"from {target_module} import *  # noqa: F401,F403\n"
    )


def main():
    dry_run = "--dry-run" in sys.argv
    os.chdir(REPO_ROOT)

    shims = []
    orphans = []
    oversized = []
    coverage_with = []
    coverage_without = []
    errors = []

    # --- Discover all canonical runtime modules ---
    canonical = set()
    for py_file in sorted(Path(RUNTIME_DIR).rglob("*.py")):
        if "__pycache__" in str(py_file):
            continue
        canonical.add(str(py_file.relative_to(REPO_ROOT)))

    # --- Top-level modules ---
    for py_file in sorted(Path(RUNTIME_DIR).glob("*.py")):
        if py_file.name == "__init__.py":
            continue
        module = py_file.stem
        target = f"runtime.{module}"
        shim_path = os.path.join(EOS_AI_DIR, f"{module}.py")
        eos_module = f"eos_ai.{module}"

        content = _shim_content(target)
        if not dry_run:
            Path(shim_path).write_text(content)

        shims.append({
            "shim": f"eos_ai/{module}.py",
            "target": target,
            "eos_module": eos_module,
            "type": "top_level",
            "pattern": "sys.modules",
            "private_consumers": eos_module in PRIVATE_NAME_CONSUMERS,
        })
        coverage_with.append(f"runtime/{module}.py")

    # --- transport/ subpackage ---
    transport_dir = os.path.join(RUNTIME_DIR, "transport")
    eos_transport_dir = os.path.join(EOS_AI_DIR, "transport")
    os.makedirs(eos_transport_dir, exist_ok=True)

    # transport/__init__.py
    init_target = "runtime.transport"
    init_content = _init_shim_content(init_target)
    init_path = os.path.join(eos_transport_dir, "__init__.py")
    if not dry_run:
        Path(init_path).write_text(init_content)
    shims.append({
        "shim": "eos_ai/transport/__init__.py",
        "target": init_target,
        "eos_module": "eos_ai.transport",
        "type": "transport_init",
        "pattern": "import_star",
        "private_consumers": False,
    })

    for py_file in sorted(Path(transport_dir).glob("*.py")):
        if py_file.name == "__init__.py":
            continue
        module = py_file.stem
        target = f"runtime.transport.{module}"
        shim_path = os.path.join(eos_transport_dir, f"{module}.py")
        eos_module = f"eos_ai.transport.{module}"

        content = _shim_content(target)
        if not dry_run:
            Path(shim_path).write_text(content)

        shims.append({
            "shim": f"eos_ai/transport/{module}.py",
            "target": target,
            "eos_module": eos_module,
            "type": "transport",
            "pattern": "sys.modules",
            "private_consumers": eos_module in PRIVATE_NAME_CONSUMERS,
        })
        coverage_with.append(f"runtime/transport/{module}.py")

    # --- substrate/ subpackage ---
    substrate_dir = os.path.join(RUNTIME_DIR, "substrate")
    eos_substrate_dir = os.path.join(EOS_AI_DIR, "substrate")
    os.makedirs(eos_substrate_dir, exist_ok=True)

    # substrate/__init__.py → runtime.substrate
    sub_init_target = "runtime.substrate"
    sub_init_content = _init_shim_content(sub_init_target)
    sub_init_path = os.path.join(eos_substrate_dir, "__init__.py")
    if not dry_run:
        Path(sub_init_path).write_text(sub_init_content)
    shims.append({
        "shim": "eos_ai/substrate/__init__.py",
        "target": sub_init_target,
        "eos_module": "eos_ai.substrate",
        "type": "substrate_init",
        "pattern": "import_star",
        "private_consumers": False,
    })

    for py_file in sorted(Path(substrate_dir).glob("*.py")):
        if py_file.name == "__init__.py":
            continue
        module = py_file.stem
        target = f"runtime.substrate.{module}"
        shim_path = os.path.join(eos_substrate_dir, f"{module}.py")
        eos_module = f"eos_ai.substrate.{module}"

        content = _shim_content(target)
        if not dry_run:
            Path(shim_path).write_text(content)

        shims.append({
            "shim": f"eos_ai/substrate/{module}.py",
            "target": target,
            "eos_module": eos_module,
            "type": "substrate",
            "pattern": "sys.modules",
            "private_consumers": eos_module in PRIVATE_NAME_CONSUMERS,
        })
        coverage_with.append(f"runtime/substrate/{module}.py")

    # --- interfaces/ subpackage ---
    interfaces_dir = os.path.join(RUNTIME_DIR, "interfaces")
    eos_interfaces_dir = os.path.join(EOS_AI_DIR, "interfaces")
    os.makedirs(eos_interfaces_dir, exist_ok=True)

    # interfaces/__init__.py — runtime has no __init__.py here
    if os.path.exists(os.path.join(interfaces_dir, "__init__.py")):
        iface_init_target = "runtime.interfaces"
        iface_init_content = _init_shim_content(iface_init_target)
    else:
        iface_init_content = f"{HEADER}# runtime.interfaces has no __init__.py — empty package marker\n"
    iface_init_path = os.path.join(eos_interfaces_dir, "__init__.py")
    if not dry_run:
        Path(iface_init_path).write_text(iface_init_content)
    shims.append({
        "shim": "eos_ai/interfaces/__init__.py",
        "target": "runtime.interfaces (no __init__.py)",
        "eos_module": "eos_ai.interfaces",
        "type": "interfaces_init",
        "pattern": "empty_marker",
        "private_consumers": False,
    })

    for py_file in sorted(Path(interfaces_dir).glob("*.py")):
        if py_file.name == "__init__.py":
            continue
        module = py_file.stem
        target = f"runtime.interfaces.{module}"
        shim_path = os.path.join(eos_interfaces_dir, f"{module}.py")
        eos_module = f"eos_ai.interfaces.{module}"

        content = _shim_content(target)
        if not dry_run:
            Path(shim_path).write_text(content)

        shims.append({
            "shim": f"eos_ai/interfaces/{module}.py",
            "target": target,
            "eos_module": eos_module,
            "type": "interfaces",
            "pattern": "sys.modules",
            "private_consumers": False,
        })
        coverage_with.append(f"runtime/interfaces/{module}.py")

    # --- Depth-flattened: eos_ai/runtime/ → runtime/ ---
    eos_runtime_dir = os.path.join(EOS_AI_DIR, "runtime")
    os.makedirs(eos_runtime_dir, exist_ok=True)

    # eos_ai/runtime/__init__.py (package marker)
    runtime_init_content = f"{HEADER}# Package marker for eos_ai.runtime depth-flattened shims\n"
    runtime_init_path = os.path.join(eos_runtime_dir, "__init__.py")
    if not dry_run:
        Path(runtime_init_path).write_text(runtime_init_content)
    shims.append({
        "shim": "eos_ai/runtime/__init__.py",
        "target": "N/A (package marker)",
        "eos_module": "eos_ai.runtime",
        "type": "depth_flat_init",
        "pattern": "package_marker",
        "private_consumers": False,
    })

    for flat_module in ["work_state", "provider_state"]:
        target = f"runtime.{flat_module}"
        shim_path = os.path.join(eos_runtime_dir, f"{flat_module}.py")
        eos_module = f"eos_ai.runtime.{flat_module}"

        content = _shim_content(target)
        if not dry_run:
            Path(shim_path).write_text(content)

        shims.append({
            "shim": f"eos_ai/runtime/{flat_module}.py",
            "target": target,
            "eos_module": eos_module,
            "type": "depth_flattened",
            "pattern": "sys.modules",
            "private_consumers": eos_module in PRIVATE_NAME_CONSUMERS,
        })

    # --- Orphan detection: eos_ai/ files with no canonical target ---
    all_shim_paths = {s["shim"] for s in shims}
    for py_file in sorted(Path(EOS_AI_DIR).rglob("*.py")):
        if "__pycache__" in str(py_file):
            continue
        rel = str(py_file.relative_to(REPO_ROOT))
        if rel not in all_shim_paths:
            orphans.append(rel)

    # --- Coverage: canonical modules without shims ---
    covered = set()
    for s in shims:
        target = s["target"]
        if target in ("N/A (package marker)", "runtime.interfaces (no __init__.py)"):
            continue
        parts = target.split(".")
        if len(parts) == 2:
            covered.add(f"runtime/{parts[1]}.py")
            covered.add(f"runtime/{parts[1]}/__init__.py")
        elif len(parts) == 3:
            covered.add(f"runtime/{parts[1]}/{parts[2]}.py")
            covered.add(f"runtime/{parts[1]}/{parts[2]}/__init__.py")

    for cf in sorted(canonical):
        if cf not in covered:
            coverage_without.append(cf)

    # --- Oversized detection ---
    if not dry_run:
        for s in shims:
            shim_path = os.path.join(REPO_ROOT, s["shim"])
            if os.path.exists(shim_path):
                line_count = len(Path(shim_path).read_text().splitlines())
                if line_count > MAX_SHIM_LINES:
                    oversized.append({
                        "shim": s["shim"],
                        "lines": line_count,
                        "max": MAX_SHIM_LINES,
                    })

    # --- Manifest ---
    by_type = {}
    by_pattern = {}
    for s in shims:
        by_type[s["type"]] = by_type.get(s["type"], 0) + 1
        by_pattern[s["pattern"]] = by_pattern.get(s["pattern"], 0) + 1

    manifest = {
        "generated_at": time.strftime("%Y-%m-%dT%H:%M:%S"),
        "generator": "scripts/r8d_generate_shims.py",
        "total_shims": len(shims),
        "by_type": dict(sorted(by_type.items())),
        "by_pattern": dict(sorted(by_pattern.items())),
        "canonical_module_count": len(canonical),
        "covered_modules": len(covered),
        "uncovered_modules": len(coverage_without),
        "orphan_count": len(orphans),
        "oversized_count": len(oversized),
        "private_consumer_count": sum(1 for s in shims if s["private_consumers"]),
        "errors": errors,
        "shims": shims,
        "orphans": orphans,
        "oversized": oversized,
        "uncovered": coverage_without,
        "private_name_consumers": dict(sorted(PRIVATE_NAME_CONSUMERS.items())),
    }

    manifest_path = os.path.join(REPO_ROOT, "data/migration/r8d_shim_manifest.json")
    Path(manifest_path).parent.mkdir(parents=True, exist_ok=True)
    with open(manifest_path, "w") as f:
        json.dump(manifest, f, indent=2)

    # --- Print summary ---
    print(f"{'[DRY RUN] ' if dry_run else ''}Shims generated: {len(shims)}")
    for t, c in sorted(by_type.items()):
        print(f"  {t}: {c}")
    print(f"Pattern: {dict(sorted(by_pattern.items()))}")
    print(f"Canonical modules: {len(canonical)}")
    print(f"Covered: {len(covered)}, Uncovered: {len(coverage_without)}")
    print(f"Orphans: {len(orphans)}")
    if orphans:
        for o in orphans:
            print(f"  {o}")
    print(f"Oversized: {len(oversized)}")
    if oversized:
        for o in oversized:
            print(f"  {o['shim']}: {o['lines']} lines (max {o['max']})")
    print(f"Private-name consumers: {sum(1 for s in shims if s['private_consumers'])}")
    print(f"Manifest: {manifest_path}")


if __name__ == "__main__":
    main()
