#!/usr/bin/env python3
"""
build_skill_graph.py — Tool Mastery Engine skill dependency graph.

Builds a cross-reference graph between tool skills by scanning each
skill's SKILL.md + references/best_practices.md for mentions of
*other* tool slugs. Mentions come from:

  1. Explicit word-boundary matches of another skill's slug
  2. Word-boundary matches of the skill's title / frontmatter name
  3. Common alias rewrites (e.g. "postgres" → neon_postgres)

The result is a directed graph (slug → {slugs it references}) plus
reverse index and centrality. Written as both markdown (human) and
JSON (machine).

Outputs:
  /opt/OS/docs/system/skill_graph.md
  /opt/OS/docs/system/skill_graph.json

Usage:
    python3 scripts/build_skill_graph.py            # write both files
    python3 scripts/build_skill_graph.py --stdout   # print markdown
    python3 scripts/build_skill_graph.py --skill notion  # deps of one skill
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from collections import defaultdict
from pathlib import Path

sys.path.insert(0, "/opt/OS")

from scripts._tme_common import (  # noqa: E402
    SkillRecord,
    all_skill_slugs,
    load_all_skills,
    load_skill,
)

OUT_DIR = Path("/opt/OS/docs/system")
OUT_MD = OUT_DIR / "skill_graph.md"
OUT_JSON = OUT_DIR / "skill_graph.json"

# Extra alias tokens → canonical slug. Kept small and conservative —
# only aliases known to be unambiguous in EOS context.
ALIASES: dict[str, str] = {
    "postgres": "neon_postgres",
    "postgresql": "neon_postgres",
    "neon": "neon_postgres",
    "gsheets": "google_sheets",
    "gcp": "google_cloud",
}

# Tokens that look like tool slugs but would false-match common words
STOPWORD_SLUGS = {"git", "python", "bash", "cron"}  # still indexed, but noisy


def _tokens_for(rec: SkillRecord) -> set[str]:
    """Return lowercase match tokens for this skill (slug + title words)."""
    tokens = {rec.slug.lower(), rec.slug.replace("_", " ").lower()}
    name = str(rec.frontmatter.get("name", "")).strip().lower()
    if name:
        tokens.add(name)
    # Title from H1
    for line in rec.skill_body.splitlines():
        s = line.strip()
        if s.startswith("# "):
            tokens.add(s[2:].strip().lower())
            break
    tokens = {t for t in tokens if t and len(t) >= 3}
    return tokens


def _find_refs(source: SkillRecord, all_tokens: dict[str, str]) -> set[str]:
    """
    Scan source's SKILL.md body + best_practices body for mentions of
    any other skill's tokens. Returns the set of referenced slugs
    (excluding the source itself).
    """
    haystack = (source.skill_body + "\n" + source.bp_body).lower()
    refs: set[str] = set()
    for token, target_slug in all_tokens.items():
        if target_slug == source.slug:
            continue
        # Word-boundary match. For multi-word tokens, \b on both sides.
        pattern = r"\b" + re.escape(token) + r"\b"
        if re.search(pattern, haystack):
            refs.add(target_slug)
    # Alias pass
    for alias, canonical in ALIASES.items():
        if canonical == source.slug:
            continue
        if re.search(r"\b" + re.escape(alias) + r"\b", haystack):
            refs.add(canonical)
    return refs


def build_graph(skills: list[SkillRecord]) -> dict:
    # Build token → slug map. When multiple skills share a token (rare),
    # the longer/more-specific slug wins.
    token_map: dict[str, str] = {}
    for rec in skills:
        for tok in _tokens_for(rec):
            existing = token_map.get(tok)
            if existing is None or len(rec.slug) > len(existing):
                token_map[tok] = rec.slug

    outgoing: dict[str, set[str]] = {}
    for rec in skills:
        outgoing[rec.slug] = _find_refs(rec, token_map)

    incoming: dict[str, set[str]] = defaultdict(set)
    for src, targets in outgoing.items():
        for t in targets:
            incoming[t].add(src)

    centrality = {
        slug: len(outgoing.get(slug, set())) + len(incoming.get(slug, set()))
        for slug in [r.slug for r in skills]
    }
    orphans = [
        slug
        for slug in [r.slug for r in skills]
        if not outgoing.get(slug) and not incoming.get(slug)
    ]

    return {
        "nodes": [r.slug for r in skills],
        "edges": {k: sorted(v) for k, v in outgoing.items()},
        "reverse_edges": {k: sorted(v) for k, v in incoming.items()},
        "centrality": centrality,
        "orphans": sorted(orphans),
    }


def render_markdown(graph: dict) -> str:
    lines: list[str] = []
    lines.append("# Tool Mastery Engine — Skill Dependency Graph\n")
    lines.append(
        "_Auto-generated by `scripts/build_skill_graph.py`. "
        "Edges are derived from slug/title mentions in SKILL.md + best_practices.md._\n"
    )

    # Top 20 central skills
    top = sorted(
        graph["centrality"].items(), key=lambda kv: kv[1], reverse=True
    )[:20]
    lines.append("## Core skills (highest centrality)\n")
    lines.append("| Skill | Degree | Out | In |")
    lines.append("|---|---|---|---|")
    for slug, deg in top:
        out_n = len(graph["edges"].get(slug, []))
        in_n = len(graph["reverse_edges"].get(slug, []))
        lines.append(f"| `{slug}` | {deg} | {out_n} | {in_n} |")
    lines.append("")

    lines.append("## Orphaned skills (no mentions in either direction)\n")
    if graph["orphans"]:
        for slug in graph["orphans"]:
            lines.append(f"- `{slug}`")
    else:
        lines.append("_None — every skill is connected._")
    lines.append("")

    lines.append("## Full adjacency\n")
    for slug in sorted(graph["nodes"]):
        out = graph["edges"].get(slug, [])
        if not out:
            continue
        lines.append(f"### `{slug}`")
        lines.append(", ".join(f"`{t}`" for t in out))
        lines.append("")
    return "\n".join(lines) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--stdout", action="store_true", help="print markdown, don't write files")
    ap.add_argument("--skill", metavar="SLUG", help="show deps for one skill only")
    args = ap.parse_args()

    skills = load_all_skills()
    graph = build_graph(skills)

    if args.skill:
        out = graph["edges"].get(args.skill, [])
        inc = graph["reverse_edges"].get(args.skill, [])
        print(f"# {args.skill}")
        print(f"references: {', '.join(out) or '—'}")
        print(f"referenced by: {', '.join(inc) or '—'}")
        return 0

    md = render_markdown(graph)
    if args.stdout:
        print(md)
        return 0

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    OUT_MD.write_text(md, encoding="utf-8")
    OUT_JSON.write_text(json.dumps(graph, indent=2, sort_keys=True), encoding="utf-8")
    print(f"Wrote {OUT_MD}")
    print(f"Wrote {OUT_JSON}")
    print(
        f"Nodes={len(graph['nodes'])} "
        f"edges={sum(len(v) for v in graph['edges'].values())} "
        f"orphans={len(graph['orphans'])}"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
