#!/usr/bin/env python3
"""Codegen: generate the TS mirror of the canonical VoiceErrorCode enum.

P4S31 Voice Convergence. The Python enum
``substrate/execution/voice/error_codes.py::VoiceErrorCode`` is the single source
of truth for voice error codes across the whole system. This script regenerates
``cockpit/src/renderer/api/voiceErrorCodes.ts`` from it so the client and server
can never disagree (this kills the ``groq_whisper``-label-mismatch class of bug).

Contract:
- Deterministic: same enum in → byte-identical TS out (sorted by definition
  order, fixed header, LF newlines).
- Codegen-checked in CI/pre-commit via:
      python3 scripts/gen_voice_error_codes_ts.py && git diff --exit-code \
        cockpit/src/renderer/api/voiceErrorCodes.ts
  A hand-edit of the TS or a new Python code without regenerating fails the diff.

Usage:
    python3 scripts/gen_voice_error_codes_ts.py          # write the file
    python3 scripts/gen_voice_error_codes_ts.py --check   # exit 1 if out of date
"""

from __future__ import annotations

import sys
from pathlib import Path

_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(_ROOT))

from substrate.execution.voice.error_codes import VoiceErrorCode  # noqa: E402

_OUT = _ROOT / "cockpit" / "src" / "renderer" / "api" / "voiceErrorCodes.ts"

_HEADER = """\
// AUTO-GENERATED by scripts/gen_voice_error_codes_ts.py — DO NOT EDIT BY HAND.
// Source of truth: substrate/execution/voice/error_codes.py::VoiceErrorCode
// Regenerate: python3 scripts/gen_voice_error_codes_ts.py
// The canonical voice error taxonomy, mirrored 1:1 from the Python enum so the
// governed WS relays a code the client already knows — no remapping, ever.
"""


def render() -> str:
    """Render the TS mirror as a deterministic string (LF newlines)."""
    members = list(VoiceErrorCode)  # definition order
    lines: list[str] = [_HEADER, ""]
    lines.append("export const VOICE_ERROR_CODES = {")
    for c in members:
        # name === value for every canonical code (enforced by the enum + gate).
        lines.append(f'  {c.name}: "{c.value}",')
    lines.append("} as const")
    lines.append("")
    lines.append("export type VoiceErrorCode =")
    lines.append("  (typeof VOICE_ERROR_CODES)[keyof typeof VOICE_ERROR_CODES]")
    lines.append("")
    lines.append("export const VOICE_ERROR_CODE_VALUES: readonly VoiceErrorCode[] =")
    lines.append("  Object.values(VOICE_ERROR_CODES)")
    lines.append("")
    lines.append("export function isVoiceErrorCode(x: unknown): x is VoiceErrorCode {")
    lines.append(
        '  return typeof x === "string" && '
        "(VOICE_ERROR_CODE_VALUES as readonly string[]).includes(x)"
    )
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    check = "--check" in sys.argv
    rendered = render()
    if check:
        current = _OUT.read_text(encoding="utf-8") if _OUT.exists() else ""
        if current != rendered:
            print(
                "voiceErrorCodes.ts is out of date — run "
                "`python3 scripts/gen_voice_error_codes_ts.py`",
                file=sys.stderr,
            )
            return 1
        print("voiceErrorCodes.ts up to date")
        return 0
    _OUT.parent.mkdir(parents=True, exist_ok=True)
    _OUT.write_text(rendered, encoding="utf-8")
    print(f"wrote {_OUT.relative_to(_ROOT)} ({len(list(VoiceErrorCode))} codes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
