"""Phase 87B source registry — seed maps and default IngestionSource objects.

Pre-built source configurations for common platforms. Tool-agnostic —
each entry describes the source class + platform, not a specific user's
account. Users select which sources apply during onboarding.

Advisory/planning only. No scraping. No API calls. No account connections.
No file reading. No memory promotion. No execution.
"""

from __future__ import annotations

from umh.ingestion.contracts import (
    AccessMethod,
    IngestionPriority,
    IngestionSource,
    MemoryPromotionPolicy,
    OnboardingTier,
    PermissionScope,
    PlatformType,
    RefreshCadence,
    ReviewRequirement,
    SourceClass,
    SourceModality,
    SourceSensitivity,
    SourceStatus,
    _ingest_id,
)


def build_seed_sources() -> list[IngestionSource]:
    return [
        IngestionSource(
            source_id=_ingest_id("src"),
            source_class=SourceClass.EMAIL,
            platform=PlatformType.GMAIL,
            name="Gmail",
            description="Google email — conversations, threads, attachments",
            modalities=[SourceModality.TEXT, SourceModality.RICH_TEXT],
            access_methods=[AccessMethod.OFFICIAL_API, AccessMethod.OAUTH],
            permission_scopes=[PermissionScope.READ_ONLY],
            onboarding_tier=OnboardingTier.TIER_2_WORKSPACE,
            priority=IngestionPriority.HIGH,
            sensitivity=SourceSensitivity.CONFIDENTIAL,
            review_requirement=ReviewRequirement.SAMPLE_REVIEW,
            promotion_policy=MemoryPromotionPolicy.CONFIDENCE_THRESHOLD,
            status=SourceStatus.DISCOVERED,
            refresh_cadence=RefreshCadence.DAILY,
        ),
        IngestionSource(
            source_id=_ingest_id("src"),
            source_class=SourceClass.CALENDAR,
            platform=PlatformType.GOOGLE_CALENDAR,
            name="Google Calendar",
            description="Google calendar events, meetings, scheduling",
            modalities=[SourceModality.STRUCTURED_DATA],
            access_methods=[AccessMethod.OFFICIAL_API, AccessMethod.OAUTH],
            permission_scopes=[PermissionScope.READ_ONLY],
            onboarding_tier=OnboardingTier.TIER_2_WORKSPACE,
            priority=IngestionPriority.HIGH,
            sensitivity=SourceSensitivity.INTERNAL,
            review_requirement=ReviewRequirement.SPOT_CHECK,
            promotion_policy=MemoryPromotionPolicy.AUTO_PROMOTE,
            status=SourceStatus.DISCOVERED,
            refresh_cadence=RefreshCadence.DAILY,
        ),
        IngestionSource(
            source_id=_ingest_id("src"),
            source_class=SourceClass.NOTE_TAKING,
            platform=PlatformType.OBSIDIAN,
            name="Obsidian Vault",
            description="Local markdown knowledge base — notes, wikis, daily logs",
            modalities=[SourceModality.TEXT, SourceModality.RICH_TEXT],
            access_methods=[AccessMethod.LOCAL_FILESYSTEM],
            permission_scopes=[PermissionScope.READ_ONLY],
            onboarding_tier=OnboardingTier.TIER_1_LOCAL_ARCHIVES,
            priority=IngestionPriority.HIGH,
            sensitivity=SourceSensitivity.INTERNAL,
            review_requirement=ReviewRequirement.SAMPLE_REVIEW,
            promotion_policy=MemoryPromotionPolicy.CONFIDENCE_THRESHOLD,
            status=SourceStatus.DISCOVERED,
            refresh_cadence=RefreshCadence.WEEKLY,
        ),
        IngestionSource(
            source_id=_ingest_id("src"),
            source_class=SourceClass.NOTE_TAKING,
            platform=PlatformType.NOTION,
            name="Notion Workspace",
            description="Notion databases, pages, wikis",
            modalities=[
                SourceModality.TEXT,
                SourceModality.RICH_TEXT,
                SourceModality.STRUCTURED_DATA,
            ],
            access_methods=[AccessMethod.OFFICIAL_API, AccessMethod.API_KEY],
            permission_scopes=[PermissionScope.READ_ONLY],
            onboarding_tier=OnboardingTier.TIER_2_WORKSPACE,
            priority=IngestionPriority.HIGH,
            sensitivity=SourceSensitivity.INTERNAL,
            review_requirement=ReviewRequirement.SAMPLE_REVIEW,
            promotion_policy=MemoryPromotionPolicy.CONFIDENCE_THRESHOLD,
            status=SourceStatus.DISCOVERED,
            refresh_cadence=RefreshCadence.DAILY,
        ),
        IngestionSource(
            source_id=_ingest_id("src"),
            source_class=SourceClass.CODE_REPOSITORY,
            platform=PlatformType.GITHUB,
            name="GitHub Repositories",
            description="Git repos — code, PRs, issues, commits",
            modalities=[SourceModality.CODE, SourceModality.TEXT],
            access_methods=[AccessMethod.OFFICIAL_API, AccessMethod.API_KEY],
            permission_scopes=[PermissionScope.READ_ONLY],
            onboarding_tier=OnboardingTier.TIER_2_WORKSPACE,
            priority=IngestionPriority.HIGH,
            sensitivity=SourceSensitivity.INTERNAL,
            review_requirement=ReviewRequirement.SPOT_CHECK,
            promotion_policy=MemoryPromotionPolicy.AUTO_PROMOTE,
            status=SourceStatus.DISCOVERED,
            refresh_cadence=RefreshCadence.DAILY,
        ),
        IngestionSource(
            source_id=_ingest_id("src"),
            source_class=SourceClass.MESSAGING,
            platform=PlatformType.DISCORD,
            name="Discord",
            description="Discord servers, DMs, channels",
            modalities=[SourceModality.CONVERSATION, SourceModality.TEXT],
            access_methods=[AccessMethod.OFFICIAL_API, AccessMethod.WEBHOOK],
            permission_scopes=[PermissionScope.READ_ONLY],
            onboarding_tier=OnboardingTier.TIER_2_WORKSPACE,
            priority=IngestionPriority.HIGH,
            sensitivity=SourceSensitivity.CONFIDENTIAL,
            review_requirement=ReviewRequirement.SAMPLE_REVIEW,
            promotion_policy=MemoryPromotionPolicy.HUMAN_REVIEW,
            status=SourceStatus.DISCOVERED,
            refresh_cadence=RefreshCadence.DAILY,
        ),
        IngestionSource(
            source_id=_ingest_id("src"),
            source_class=SourceClass.MESSAGING,
            platform=PlatformType.TELEGRAM,
            name="Telegram",
            description="Telegram chats, groups, channels",
            modalities=[SourceModality.CONVERSATION, SourceModality.TEXT],
            access_methods=[AccessMethod.OFFICIAL_API, AccessMethod.WEBHOOK],
            permission_scopes=[PermissionScope.READ_ONLY],
            onboarding_tier=OnboardingTier.TIER_2_WORKSPACE,
            priority=IngestionPriority.HIGH,
            sensitivity=SourceSensitivity.CONFIDENTIAL,
            review_requirement=ReviewRequirement.SAMPLE_REVIEW,
            promotion_policy=MemoryPromotionPolicy.HUMAN_REVIEW,
            status=SourceStatus.DISCOVERED,
            refresh_cadence=RefreshCadence.DAILY,
        ),
        IngestionSource(
            source_id=_ingest_id("src"),
            source_class=SourceClass.SOCIAL_MEDIA,
            platform=PlatformType.INSTAGRAM,
            name="Instagram",
            description="Instagram posts, stories, reels, saved content",
            modalities=[
                SourceModality.IMAGE,
                SourceModality.VIDEO,
                SourceModality.TEXT,
                SourceModality.FEED,
            ],
            access_methods=[AccessMethod.BROWSER_SESSION, AccessMethod.EXPORT_FILE],
            permission_scopes=[PermissionScope.READ_ONLY],
            onboarding_tier=OnboardingTier.TIER_3_SOCIAL_ALGORITHM,
            priority=IngestionPriority.MEDIUM,
            sensitivity=SourceSensitivity.PUBLIC,
            review_requirement=ReviewRequirement.SAMPLE_REVIEW,
            promotion_policy=MemoryPromotionPolicy.BATCH_REVIEW,
            status=SourceStatus.DISCOVERED,
            refresh_cadence=RefreshCadence.DAILY,
        ),
        IngestionSource(
            source_id=_ingest_id("src"),
            source_class=SourceClass.SOCIAL_MEDIA,
            platform=PlatformType.TWITTER,
            name="Twitter / X",
            description="Tweets, threads, bookmarks, lists",
            modalities=[SourceModality.TEXT, SourceModality.IMAGE, SourceModality.FEED],
            access_methods=[
                AccessMethod.BROWSER_SESSION,
                AccessMethod.OFFICIAL_API,
                AccessMethod.EXPORT_FILE,
            ],
            permission_scopes=[PermissionScope.READ_ONLY],
            onboarding_tier=OnboardingTier.TIER_3_SOCIAL_ALGORITHM,
            priority=IngestionPriority.MEDIUM,
            sensitivity=SourceSensitivity.PUBLIC,
            review_requirement=ReviewRequirement.SAMPLE_REVIEW,
            promotion_policy=MemoryPromotionPolicy.BATCH_REVIEW,
            status=SourceStatus.DISCOVERED,
            refresh_cadence=RefreshCadence.DAILY,
        ),
        IngestionSource(
            source_id=_ingest_id("src"),
            source_class=SourceClass.SOCIAL_MEDIA,
            platform=PlatformType.LINKEDIN,
            name="LinkedIn",
            description="LinkedIn posts, messages, connections, saved items",
            modalities=[SourceModality.TEXT, SourceModality.FEED],
            access_methods=[AccessMethod.BROWSER_SESSION, AccessMethod.EXPORT_FILE],
            permission_scopes=[PermissionScope.READ_ONLY],
            onboarding_tier=OnboardingTier.TIER_3_SOCIAL_ALGORITHM,
            priority=IngestionPriority.MEDIUM,
            sensitivity=SourceSensitivity.PUBLIC,
            review_requirement=ReviewRequirement.SAMPLE_REVIEW,
            promotion_policy=MemoryPromotionPolicy.BATCH_REVIEW,
            status=SourceStatus.DISCOVERED,
            refresh_cadence=RefreshCadence.DAILY,
        ),
        IngestionSource(
            source_id=_ingest_id("src"),
            source_class=SourceClass.SOCIAL_MEDIA,
            platform=PlatformType.TIKTOK,
            name="TikTok",
            description="TikTok videos, saved content, liked videos",
            modalities=[SourceModality.VIDEO, SourceModality.TEXT, SourceModality.FEED],
            access_methods=[AccessMethod.BROWSER_SESSION, AccessMethod.EXPORT_FILE],
            permission_scopes=[PermissionScope.READ_ONLY],
            onboarding_tier=OnboardingTier.TIER_3_SOCIAL_ALGORITHM,
            priority=IngestionPriority.MEDIUM,
            sensitivity=SourceSensitivity.PUBLIC,
            review_requirement=ReviewRequirement.SAMPLE_REVIEW,
            promotion_policy=MemoryPromotionPolicy.BATCH_REVIEW,
            status=SourceStatus.DISCOVERED,
            refresh_cadence=RefreshCadence.DAILY,
        ),
        IngestionSource(
            source_id=_ingest_id("src"),
            source_class=SourceClass.VIDEO_PLATFORM,
            platform=PlatformType.YOUTUBE,
            name="YouTube",
            description="YouTube subscriptions, watch history, playlists, liked videos",
            modalities=[SourceModality.VIDEO, SourceModality.TEXT],
            access_methods=[AccessMethod.OFFICIAL_API, AccessMethod.RSS],
            permission_scopes=[PermissionScope.READ_ONLY],
            onboarding_tier=OnboardingTier.TIER_3_SOCIAL_ALGORITHM,
            priority=IngestionPriority.LOW,
            sensitivity=SourceSensitivity.PUBLIC,
            review_requirement=ReviewRequirement.SPOT_CHECK,
            promotion_policy=MemoryPromotionPolicy.BATCH_REVIEW,
            status=SourceStatus.DISCOVERED,
            refresh_cadence=RefreshCadence.WEEKLY,
        ),
        IngestionSource(
            source_id=_ingest_id("src"),
            source_class=SourceClass.PAYMENT_PROCESSING,
            platform=PlatformType.STRIPE,
            name="Stripe",
            description="Stripe payments, subscriptions, invoices, customers",
            modalities=[SourceModality.TRANSACTION, SourceModality.STRUCTURED_DATA],
            access_methods=[AccessMethod.OFFICIAL_API, AccessMethod.API_KEY],
            permission_scopes=[PermissionScope.READ_ONLY, PermissionScope.READ_TRANSACTIONS],
            onboarding_tier=OnboardingTier.TIER_2_WORKSPACE,
            priority=IngestionPriority.CRITICAL,
            sensitivity=SourceSensitivity.FINANCIAL,
            review_requirement=ReviewRequirement.FULL_REVIEW,
            promotion_policy=MemoryPromotionPolicy.HUMAN_REVIEW,
            status=SourceStatus.DISCOVERED,
            refresh_cadence=RefreshCadence.DAILY,
        ),
        IngestionSource(
            source_id=_ingest_id("src"),
            source_class=SourceClass.AI_ASSISTANT,
            platform=PlatformType.CHATGPT,
            name="ChatGPT Export",
            description="ChatGPT conversation exports — decisions, research, ideas",
            modalities=[SourceModality.CONVERSATION, SourceModality.TEXT, SourceModality.CODE],
            access_methods=[AccessMethod.EXPORT_FILE],
            permission_scopes=[PermissionScope.READ_ONLY],
            onboarding_tier=OnboardingTier.TIER_1_LOCAL_ARCHIVES,
            priority=IngestionPriority.HIGH,
            sensitivity=SourceSensitivity.CONFIDENTIAL,
            review_requirement=ReviewRequirement.SAMPLE_REVIEW,
            promotion_policy=MemoryPromotionPolicy.SUPERSESSION_CHECK,
            status=SourceStatus.DISCOVERED,
            refresh_cadence=RefreshCadence.ONE_TIME,
        ),
        IngestionSource(
            source_id=_ingest_id("src"),
            source_class=SourceClass.AI_ASSISTANT,
            platform=PlatformType.CLAUDE,
            name="Claude Export",
            description="Claude conversation exports — decisions, research, architecture",
            modalities=[SourceModality.CONVERSATION, SourceModality.TEXT, SourceModality.CODE],
            access_methods=[AccessMethod.EXPORT_FILE],
            permission_scopes=[PermissionScope.READ_ONLY],
            onboarding_tier=OnboardingTier.TIER_1_LOCAL_ARCHIVES,
            priority=IngestionPriority.HIGH,
            sensitivity=SourceSensitivity.CONFIDENTIAL,
            review_requirement=ReviewRequirement.SAMPLE_REVIEW,
            promotion_policy=MemoryPromotionPolicy.SUPERSESSION_CHECK,
            status=SourceStatus.DISCOVERED,
            refresh_cadence=RefreshCadence.ONE_TIME,
        ),
        IngestionSource(
            source_id=_ingest_id("src"),
            source_class=SourceClass.CLOUD_STORAGE,
            platform=PlatformType.GOOGLE_DRIVE,
            name="Google Drive",
            description="Google Drive files, folders, shared documents",
            modalities=[SourceModality.TEXT, SourceModality.IMAGE, SourceModality.PDF],
            access_methods=[AccessMethod.OFFICIAL_API, AccessMethod.OAUTH],
            permission_scopes=[PermissionScope.READ_ONLY],
            onboarding_tier=OnboardingTier.TIER_2_WORKSPACE,
            priority=IngestionPriority.MEDIUM,
            sensitivity=SourceSensitivity.INTERNAL,
            review_requirement=ReviewRequirement.SAMPLE_REVIEW,
            promotion_policy=MemoryPromotionPolicy.CONFIDENCE_THRESHOLD,
            status=SourceStatus.DISCOVERED,
            refresh_cadence=RefreshCadence.WEEKLY,
        ),
        IngestionSource(
            source_id=_ingest_id("src"),
            source_class=SourceClass.NOTE_TAKING,
            platform=PlatformType.APPLE_NOTES,
            name="Apple Notes",
            description="Apple Notes — local notes from iOS/macOS",
            modalities=[SourceModality.TEXT, SourceModality.RICH_TEXT, SourceModality.IMAGE],
            access_methods=[AccessMethod.LOCAL_FILESYSTEM, AccessMethod.EXPORT_FILE],
            permission_scopes=[PermissionScope.READ_ONLY],
            onboarding_tier=OnboardingTier.TIER_1_LOCAL_ARCHIVES,
            priority=IngestionPriority.HIGH,
            sensitivity=SourceSensitivity.INTERNAL,
            review_requirement=ReviewRequirement.SAMPLE_REVIEW,
            promotion_policy=MemoryPromotionPolicy.CONFIDENCE_THRESHOLD,
            status=SourceStatus.DISCOVERED,
            refresh_cadence=RefreshCadence.WEEKLY,
        ),
        IngestionSource(
            source_id=_ingest_id("src"),
            source_class=SourceClass.ANALYTICS,
            platform=PlatformType.GOOGLE_ANALYTICS,
            name="Google Analytics",
            description="Website/app analytics — traffic, conversions, user behavior",
            modalities=[SourceModality.STRUCTURED_DATA],
            access_methods=[AccessMethod.OFFICIAL_API, AccessMethod.OAUTH],
            permission_scopes=[PermissionScope.READ_ANALYTICS],
            onboarding_tier=OnboardingTier.TIER_2_WORKSPACE,
            priority=IngestionPriority.MEDIUM,
            sensitivity=SourceSensitivity.INTERNAL,
            review_requirement=ReviewRequirement.SPOT_CHECK,
            promotion_policy=MemoryPromotionPolicy.AUTO_PROMOTE,
            status=SourceStatus.DISCOVERED,
            refresh_cadence=RefreshCadence.DAILY,
        ),
        IngestionSource(
            source_id=_ingest_id("src"),
            source_class=SourceClass.CONTAINER_RUNTIME,
            platform=PlatformType.DOCKER,
            name="Docker Logs",
            description="Docker container logs, service health, deployment events",
            modalities=[SourceModality.TEXT, SourceModality.STRUCTURED_DATA],
            access_methods=[AccessMethod.LOCAL_FILESYSTEM],
            permission_scopes=[PermissionScope.READ_ONLY],
            onboarding_tier=OnboardingTier.TIER_2_WORKSPACE,
            priority=IngestionPriority.LOW,
            sensitivity=SourceSensitivity.INTERNAL,
            review_requirement=ReviewRequirement.NONE,
            promotion_policy=MemoryPromotionPolicy.NEVER_PROMOTE,
            status=SourceStatus.DISCOVERED,
            refresh_cadence=RefreshCadence.ON_DEMAND,
        ),
        IngestionSource(
            source_id=_ingest_id("src"),
            source_class=SourceClass.TASK_MANAGEMENT,
            platform=PlatformType.CALENDLY,
            name="Calendly",
            description="Scheduling — bookings, availability, event types",
            modalities=[SourceModality.STRUCTURED_DATA],
            access_methods=[AccessMethod.OFFICIAL_API, AccessMethod.WEBHOOK],
            permission_scopes=[PermissionScope.READ_ONLY],
            onboarding_tier=OnboardingTier.TIER_2_WORKSPACE,
            priority=IngestionPriority.MEDIUM,
            sensitivity=SourceSensitivity.INTERNAL,
            review_requirement=ReviewRequirement.SPOT_CHECK,
            promotion_policy=MemoryPromotionPolicy.AUTO_PROMOTE,
            status=SourceStatus.DISCOVERED,
            refresh_cadence=RefreshCadence.DAILY,
        ),
    ]


def get_sources_by_tier(
    tier: OnboardingTier,
    sources: list[IngestionSource] | None = None,
) -> list[IngestionSource]:
    if sources is None:
        sources = build_seed_sources()
    return [s for s in sources if s.onboarding_tier == tier]


def get_sources_by_class(
    source_class: SourceClass,
    sources: list[IngestionSource] | None = None,
) -> list[IngestionSource]:
    if sources is None:
        sources = build_seed_sources()
    return [s for s in sources if s.source_class == source_class]


def get_sources_by_sensitivity(
    sensitivity: SourceSensitivity,
    sources: list[IngestionSource] | None = None,
) -> list[IngestionSource]:
    if sources is None:
        sources = build_seed_sources()
    return [s for s in sources if s.sensitivity == sensitivity]


def get_financial_sources(
    sources: list[IngestionSource] | None = None,
) -> list[IngestionSource]:
    return get_sources_by_sensitivity(SourceSensitivity.FINANCIAL, sources)


def get_high_priority_sources(
    sources: list[IngestionSource] | None = None,
) -> list[IngestionSource]:
    if sources is None:
        sources = build_seed_sources()
    return [
        s for s in sources if s.priority in (IngestionPriority.CRITICAL, IngestionPriority.HIGH)
    ]
