"""UMH Plan Reviewer Agent — pre-execution plan review with structured feedback.

Reviews an ExecutionPlan BEFORE execution. Produces deterministic checks for
step count, shell commands, approval gates, execution class consistency,
missing inputs, plan source, and confidence. Optionally enhances with LLM
analysis via lightweight_execute.

READ-ONLY. ADVISORY. STATELESS. Never calls execute(). Never mutates state.
"""

from __future__ import annotations

import json
import logging
from typing import Any

from umh.agents.base import AgentOutput, AgentRole, BaseAgent
from umh.planning.validator import _APPROVAL_GATED_OPS

_log = logging.getLogger(__name__)

# Operations that require specific inputs
_REQUIRED_INPUTS: dict[str, list[str]] = {
    "shell_command": ["command"],
    "file_read": ["path"],
    "file_write": ["path", "content"],
    "file_delete": ["path"],
    "file_stat": ["path"],
    "http_request": ["url"],
}

# Side-effect operations that must use side_effect execution class
_SIDE_EFFECT_OPS: frozenset[str] = frozenset(
    {
        "shell_command",
        "file_write",
        "file_delete",
        *_APPROVAL_GATED_OPS,
    }
)


def _build_issues(plan: dict, objective: str) -> list[dict[str, Any]]:
    """Run all deterministic checks and return a list of issue dicts."""
    issues: list[dict[str, Any]] = []
    steps = plan.get("steps", [])

    # 1. Step count checks
    step_count = len(steps)
    if step_count > 8:
        issues.append(
            {
                "severity": "critical",
                "step_index": None,
                "message": f"Plan has {step_count} steps (>8) — high complexity risk",
            }
        )
    elif step_count > 5:
        issues.append(
            {
                "severity": "warning",
                "step_index": None,
                "message": f"Plan has {step_count} steps (>5) — consider simplification",
            }
        )

    for i, step in enumerate(steps):
        operation = step.get("operation", "")
        execution_class = step.get("execution_class", "")
        inputs = step.get("inputs", {})

        # 2. Shell command warning
        if operation == "shell_command":
            issues.append(
                {
                    "severity": "warning",
                    "step_index": i,
                    "message": f"Step {i} uses shell_command — requires allowlist validation",
                }
            )

        # 3. Approval-gated operations
        if operation in _APPROVAL_GATED_OPS:
            issues.append(
                {
                    "severity": "info",
                    "step_index": i,
                    "message": f"Step {i} ({operation}) requires approval before execution",
                }
            )

        # 4. Execution class consistency — side-effect ops must be side_effect class
        if operation in _SIDE_EFFECT_OPS and execution_class != "side_effect":
            issues.append(
                {
                    "severity": "critical",
                    "step_index": i,
                    "message": (
                        f"Step {i} ({operation}) is a side-effect operation "
                        f"but has execution_class '{execution_class}' instead of 'side_effect'"
                    ),
                }
            )

        # 5. Empty inputs check
        if operation in _REQUIRED_INPUTS:
            missing = [k for k in _REQUIRED_INPUTS[operation] if not inputs.get(k)]
            if missing:
                issues.append(
                    {
                        "severity": "critical",
                        "step_index": i,
                        "message": (
                            f"Step {i} ({operation}) missing required inputs: {', '.join(missing)}"
                        ),
                    }
                )

    # 6. Plan source check
    source = plan.get("source", "")
    if source == "llm":
        issues.append(
            {
                "severity": "warning",
                "step_index": None,
                "message": "Plan generated by LLM — treat as untrusted, verify steps",
            }
        )

    # 7. Confidence check
    confidence = plan.get("confidence", 1.0)
    if confidence < 0.3:
        issues.append(
            {
                "severity": "critical",
                "step_index": None,
                "message": f"Plan confidence is {confidence:.2f} (<0.3) — very low reliability",
            }
        )
    elif confidence < 0.5:
        issues.append(
            {
                "severity": "warning",
                "step_index": None,
                "message": f"Plan confidence is {confidence:.2f} (<0.5) — low reliability",
            }
        )

    return issues


def _compute_risk_level(issues: list[dict[str, Any]]) -> str:
    """Derive risk level from issue severities."""
    severities = {issue["severity"] for issue in issues}
    if "critical" in severities:
        return "high"
    if "warning" in severities:
        return "medium"
    return "low"


def _compute_verdict(issues: list[dict[str, Any]]) -> str:
    """Derive verdict from issue list."""
    critical_count = sum(1 for i in issues if i["severity"] == "critical")
    warning_count = sum(1 for i in issues if i["severity"] == "warning")
    if critical_count > 0:
        return "reject"
    if warning_count > 2:
        return "revise"
    return "approve"


def _build_suggestions(issues: list[dict[str, Any]], plan: dict) -> list[str]:
    """Generate actionable suggestions from issues."""
    suggestions: list[str] = []
    seen: set[str] = set()

    for issue in issues:
        msg = issue["message"]
        sev = issue["severity"]

        if "complexity risk" in msg or "consider simplification" in msg:
            key = "reduce_steps"
            if key not in seen:
                seen.add(key)
                suggestions.append("Break complex plans into smaller sub-plans")

        if "shell_command" in msg and "allowlist" in msg:
            key = "shell_allowlist"
            if key not in seen:
                seen.add(key)
                suggestions.append("Verify shell commands are in the allowlist before execution")

        if "missing required inputs" in msg:
            suggestions.append(f"Fix: {msg}")

        if "execution_class" in msg and sev == "critical":
            key = "fix_exec_class"
            if key not in seen:
                seen.add(key)
                suggestions.append(
                    "Ensure side-effect operations use execution_class 'side_effect'"
                )

        if "untrusted" in msg:
            key = "llm_verify"
            if key not in seen:
                seen.add(key)
                suggestions.append("Manually review LLM-generated plan steps before execution")

        if "confidence" in msg and "low" in msg.lower():
            key = "low_confidence"
            if key not in seen:
                seen.add(key)
                suggestions.append("Consider regenerating or manually constructing the plan")

    return suggestions


def _build_summary(verdict: str, risk_level: str, issues: list[dict[str, Any]]) -> str:
    """One-line summary of the review."""
    critical_count = sum(1 for i in issues if i["severity"] == "critical")
    warning_count = sum(1 for i in issues if i["severity"] == "warning")
    info_count = sum(1 for i in issues if i["severity"] == "info")
    return (
        f"Verdict: {verdict} | Risk: {risk_level} | "
        f"{critical_count} critical, {warning_count} warnings, {info_count} info"
    )


def _try_llm_review(
    plan: dict,
    objective: str,
    issues: list[dict[str, Any]],
    suggestions: list[str],
) -> tuple[list[dict[str, Any]], list[str], str]:
    """Attempt LLM-enhanced review.

    Returns (extra_issues, extra_suggestions, model_used).
    Falls back to empty lists if LLM is unavailable.
    """
    try:
        from umh.execution.engine import lightweight_execute
    except ImportError:
        return [], [], ""

    prompt = (
        "You are a plan reviewer for an AI execution system.\n"
        "Review this execution plan and identify any additional issues "
        "or suggestions.\n\n"
        f"Objective: {objective}\n\n"
        f"Plan:\n{json.dumps(plan, indent=2, default=str)}\n\n"
        f"Already-identified issues:\n"
        f"{json.dumps(issues, indent=2, default=str)}\n\n"
        "Respond with valid JSON only:\n"
        '{"additional_issues": [{"severity": "info|warning|critical", '
        '"step_index": null, "message": "..."}], '
        '"additional_suggestions": ["..."]}'
    )

    try:
        result = lightweight_execute(
            "validation",
            prompt,
            system="You are a deterministic plan reviewer. Return only valid JSON.",
            max_tokens=512,
        )
        if result.status.value != "succeeded":
            return [], [], ""

        response_text = result.outputs.get("response", "")
        if not response_text:
            return [], [], ""

        parsed = json.loads(response_text)
        extra_issues = parsed.get("additional_issues", [])
        extra_suggestions = parsed.get("additional_suggestions", [])
        model_used = result.model_used or ""

        # Validate issue structure
        valid_issues: list[dict[str, Any]] = []
        for item in extra_issues:
            if (
                isinstance(item, dict)
                and item.get("severity") in ("info", "warning", "critical")
                and isinstance(item.get("message"), str)
            ):
                valid_issues.append(
                    {
                        "severity": item["severity"],
                        "step_index": item.get("step_index"),
                        "message": item["message"],
                    }
                )

        valid_suggestions = [s for s in extra_suggestions if isinstance(s, str)]
        return valid_issues, valid_suggestions, model_used

    except Exception as exc:
        _log.debug("LLM review failed (non-fatal): %s", exc)
        return [], [], ""


class ReviewerAgent(BaseAgent):
    """Reviews execution plans before execution and produces structured feedback.

    Deterministic checks run always. LLM enhancement is optional and
    gracefully degrades when unavailable.
    """

    @property
    def role(self) -> AgentRole:
        return AgentRole.REVIEWER

    @property
    def description(self) -> str:
        return "Reviews execution plans for safety, correctness, and completeness"

    def run(self, input_data: dict) -> AgentOutput:
        """Review a plan and return structured feedback.

        Args:
            input_data: Must contain 'plan' (ExecutionPlan.to_dict()) and
                        'objective' (str).

        Returns:
            AgentOutput with output containing issues, risk_level,
            suggestions, verdict, and summary.
        """
        plan = input_data.get("plan", {})
        objective = input_data.get("objective", "")

        # Deterministic analysis
        issues = _build_issues(plan, objective)
        suggestions = _build_suggestions(issues, plan)

        # Optional LLM enhancement
        model_used = ""
        extra_issues, extra_suggestions, model_used = _try_llm_review(
            plan, objective, issues, suggestions
        )
        if extra_issues:
            issues.extend(extra_issues)
        if extra_suggestions:
            suggestions.extend(extra_suggestions)

        risk_level = _compute_risk_level(issues)
        verdict = _compute_verdict(issues)
        summary = _build_summary(verdict, risk_level, issues)

        # Confidence: higher if LLM contributed
        confidence = 0.8 if model_used else 0.7

        return AgentOutput(
            agent_role=self.role.value,
            agent_id="",
            output={
                "issues": issues,
                "risk_level": risk_level,
                "suggestions": suggestions,
                "verdict": verdict,
                "summary": summary,
            },
            confidence=confidence,
            model_used=model_used,
        )
